const VERIFIED_MAKER_IDS = new Set([
  "platforma",
  "bygge",
  "durov-house",
  "histhut",
  "countryhouse",
  "cuba-dom",
  "idolhouse",
  "woodalp",
  "boxmate",
  "uvhouse",
  "asterius-house",
  "smola-house",
  "ultradomspb",
  "freedom-naturi",
  "chebwood",
  "campingdom",
  "pslcomp",
  "domnasm",
  "blackmodule",
  "domm",
  "my-module",
  "4modul",
  "cubber",
  "simplehouse",
  "panoramic-home",
  "ambarn",
  "myfamilyhouse",
  "stroygrad",
  "modulcamp",
  "elmaco",
  "novator",
  "blagohouse",
  "stilnye-moduli",
]);

export const isVerifiedMaker = (makerId?: string) =>
  Boolean(makerId && VERIFIED_MAKER_IDS.has(makerId));
