// Auto-generated by scripts/generate-card-thumbnails.mjs.
// Maps project id to the lightweight first image used in project cards.

import thumb32 from "@/assets/wide-house-1__thumb.webp";
import thumb33 from "@/assets/cabin-31-1__thumb.webp";
import thumb34 from "@/assets/bear-1__thumb.webp";
import thumb35 from "@/assets/bear77-1__thumb.webp";
import thumb36 from "@/assets/bear86-1__thumb.webp";
import thumb40 from "@/assets/patio-6__thumb.webp";
import thumb41 from "@/assets/tundra-1__thumb.webp";
import thumb42 from "@/assets/sherwood-1__thumb.webp";
import thumb43 from "@/assets/senat-3__thumb.webp";
import thumb44 from "@/assets/family-suite-1__thumb.webp";
import thumb45 from "@/assets/gallant-1__thumb.webp";
import thumb46 from "@/assets/grandis-1__thumb.webp";
import thumb47 from "@/assets/glezman/larus-45__thumb.webp";
import thumb48 from "@/assets/glezman/larus-75__thumb.webp";
import thumb49 from "@/assets/glezman/larus-100__thumb.webp";
import thumb50 from "@/assets/glezman/larus-120__thumb.webp";
import thumb51 from "@/assets/glezman/larus-127__thumb.webp";
import thumb52 from "@/assets/divodom/start-30/1__thumb.webp";
import thumb53 from "@/assets/divodom/divo-34/1__thumb.webp";
import thumb54 from "@/assets/divodom/divo-51/1__thumb.webp";
import thumb55 from "@/assets/divodom/divo-64/1__thumb.webp";
import thumb56 from "@/assets/divodom/divo-88/1__thumb.webp";
import thumb57 from "@/assets/gradodom/filip-55-1__thumb.webp";
import thumb58 from "@/assets/gradodom/arktur-56-1__thumb.webp";
import thumb59 from "@/assets/gradodom/rinho-60-1__thumb.webp";
import thumb60 from "@/assets/gradodom/almaks-72-1__thumb.webp";
import thumb61 from "@/assets/gradodom/alester-73-1__thumb.webp";
import thumb62 from "@/assets/zagorodom/soul-1__thumb.webp";
import thumb63 from "@/assets/zagorodom/strong-1__thumb.webp";
import thumb64 from "@/assets/zagorodom/lumo-1__thumb.webp";
import thumb65 from "@/assets/zagorodom/happy-1__thumb.webp";
import thumb66 from "@/assets/zagorodom/favorite-1__thumb.webp";
import thumb67 from "@/assets/apa/aa-1/1__thumb.webp";
import thumb68 from "@/assets/apa/aa-2/1__thumb.webp";
import thumb69 from "@/assets/apa/aa-3/1__thumb.webp";
import thumb70 from "@/assets/apa/aa-4/1__thumb.webp";
import thumb71 from "@/assets/apa/aa-5/1__thumb.webp";
import thumb72 from "@/assets/prime-modul/barnhaus-200-2-etazha/1__thumb.webp";
import thumb73 from "@/assets/prime-modul/skandinaviya-72/1__thumb.webp";
import thumb74 from "@/assets/prime-modul/barn-42/1__thumb.webp";
import thumb75 from "@/assets/prime-modul/modern-72/1__thumb.webp";
import thumb76 from "@/assets/prime-modul/kantri-110/1__thumb.webp";
import thumb77 from "@/assets/utkino/lesnoy-32-1__thumb.webp";
import thumb78 from "@/assets/utkino/tikhiy-bereg-43-1__thumb.webp";
import thumb79 from "@/assets/utkino/bereginya-50-1__thumb.webp";
import thumb80 from "@/assets/utkino/berendey-63-1__thumb.webp";
import thumb81 from "@/assets/utkino/svetlitsa-prikamya-72-1__thumb.webp";
import thumb82 from "@/assets/teplodina/dk-122-1__thumb.webp";
import thumb83 from "@/assets/teplodina/dk-55-1__thumb.webp";
import thumb84 from "@/assets/teplodina/dk-67-1__thumb.webp";
import thumb85 from "@/assets/teplodina/dk-72-1__thumb.webp";
import thumb86 from "@/assets/teplodina/skandinaviya-1__thumb.webp";
import thumb87 from "@/assets/karkas-haus/kh-22-05/1__thumb.webp";
import thumb88 from "@/assets/karkas-haus/kh-23-10-barnhaus/1__thumb.webp";
import thumb89 from "@/assets/karkas-haus/kh-23-15-1/1__thumb.webp";
import thumb90 from "@/assets/karkas-haus/kh-23-15-2/1__thumb.webp";
import thumb91 from "@/assets/karkas-haus/kh-23-22-2/1__thumb.webp";
import thumb92 from "@/assets/ural-house/uh-skandi-120/1__thumb.webp";
import thumb93 from "@/assets/ural-house/uh-barn-92/1__thumb.webp";
import thumb94 from "@/assets/ural-house/uh-klassik-170/1__thumb.webp";
import thumb95 from "@/assets/ural-house/uh-fahverk-190/1__thumb.webp";
import thumb96 from "@/assets/ural-house/uh-klassik-76/1__thumb.webp";
import thumb97 from "@/assets/hochu-dom/dk-443-130/1__thumb.webp";
import thumb98 from "@/assets/hochu-dom/dk-387-115/1__thumb.webp";
import thumb99 from "@/assets/hochu-dom/dk-384-91/1__thumb.webp";
import thumb100 from "@/assets/hochu-dom/dk-428-127/1__thumb.webp";
import thumb101 from "@/assets/hochu-dom/dk-390-96/1__thumb.webp";
import thumb102 from "@/assets/scandiecodom/kd-1600/1__thumb.webp";
import thumb103 from "@/assets/scandiecodom/kd-1590/1__thumb.webp";
import thumb104 from "@/assets/scandiecodom/kd-1580/1__thumb.webp";
import thumb105 from "@/assets/scandiecodom/kd-1570/1__thumb.webp";
import thumb106 from "@/assets/scandiecodom/kd-1560/1__thumb.webp";
import thumb107 from "@/assets/karkas-povolzhya/madrid-3/1__thumb.webp";
import thumb108 from "@/assets/karkas-povolzhya/manchester/1__thumb.webp";
import thumb109 from "@/assets/karkas-povolzhya/stokgolm/1__thumb.webp";
import thumb110 from "@/assets/karkas-povolzhya/berlin/1__thumb.webp";
import thumb111 from "@/assets/karkas-povolzhya/london-1/1__thumb.webp";
import thumb112 from "@/assets/domoteka/glemping-barnhaus-6x7/1__thumb.webp";
import thumb113 from "@/assets/domoteka/parizh/1__thumb.webp";
import thumb114 from "@/assets/domoteka/elbrus/1__thumb.webp";
import thumb115 from "@/assets/domoteka/glemping-a-frame-6x6/1__thumb.webp";
import thumb116 from "@/assets/domoteka/fisht/1__thumb.webp";
import thumb117 from "@/assets/svoi-house/svoy-199/1__thumb.webp";
import thumb118 from "@/assets/svoi-house/svoy-layt-001/1__thumb.webp";
import thumb119 from "@/assets/svoi-house/svoy-100/1__thumb.webp";
import thumb120 from "@/assets/svoi-house/svoy-layt-004/1__thumb.webp";
import thumb121 from "@/assets/svoi-house/svoy-102-m/1__thumb.webp";
import thumb122 from "@/assets/bagrovstroy/9h15-dionis/1__thumb.webp";
import thumb123 from "@/assets/bagrovstroy/9h15-sadko/1__thumb.webp";
import thumb124 from "@/assets/bagrovstroy/10-5h11-avgust/1__thumb.webp";
import thumb125 from "@/assets/bagrovstroy/6h8-saveliy/1__thumb.webp";
import thumb126 from "@/assets/bagrovstroy/7h9-gostimir/1__thumb.webp";
import thumb127 from "@/assets/domakarkas/kd-120/1__thumb.webp";
import thumb128 from "@/assets/domakarkas/kd-119/1__thumb.webp";
import thumb129 from "@/assets/domakarkas/kd-118/1__thumb.webp";
import thumb130 from "@/assets/domakarkas/kd-117/1__thumb.webp";
import thumb131 from "@/assets/domakarkas/kd-116/1__thumb.webp";
import thumb132 from "@/assets/sk-garmoniya/vyazma/1__thumb.webp";
import thumb133 from "@/assets/sk-garmoniya/sosnovyy-bor/1__thumb.webp";
import thumb134 from "@/assets/sk-garmoniya/troitsk/1__thumb.webp";
import thumb135 from "@/assets/sk-garmoniya/vyborg/1__thumb.webp";
import thumb136 from "@/assets/sk-garmoniya/samara/1__thumb.webp";
import thumb137 from "@/assets/berest-dom/bogatyr-lk-7h9/1__thumb.webp";
import thumb138 from "@/assets/berest-dom/kareliya-2-7h9/1__thumb.webp";
import thumb139 from "@/assets/berest-dom/senator-7-5h9/1__thumb.webp";
import thumb140 from "@/assets/berest-dom/kareliya-1-7h8/1__thumb.webp";
import thumb141 from "@/assets/berest-dom/senator-2-8-5h10-5/1__thumb.webp";
import thumb142 from "@/assets/rift/dg51/1__thumb.webp";
import thumb143 from "@/assets/rift/dg50/1__thumb.webp";
import thumb144 from "@/assets/rift/xx27/1__thumb.webp";
import thumb145 from "@/assets/rift/dg49/1__thumb.webp";
import thumb146 from "@/assets/rift/xx05/1__thumb.webp";
import thumb147 from "@/assets/izbrusa/kd-38/1__thumb.webp";
import thumb148 from "@/assets/izbrusa/kd-29/1__thumb.webp";
import thumb149 from "@/assets/izbrusa/kd-41/1__thumb.webp";
import thumb150 from "@/assets/izbrusa/kd-12/1__thumb.webp";
import thumb151 from "@/assets/izbrusa/kd-36/1__thumb.webp";
import thumb152 from "@/assets/kazanstroy16/bigl/1__thumb.webp";
import thumb153 from "@/assets/kazanstroy16/diotima/1__thumb.webp";
import thumb154 from "@/assets/kazanstroy16/glenapp/1__thumb.webp";
import thumb155 from "@/assets/kazanstroy16/strakeya/1__thumb.webp";
import thumb156 from "@/assets/kazanstroy16/izabella/1__thumb.webp";
import thumb157 from "@/assets/askhome/nova-prime/1__thumb.webp";
import thumb158 from "@/assets/askhome/nova/1__thumb.webp";
import thumb159 from "@/assets/askhome/modera-prime/1__thumb.webp";
import thumb160 from "@/assets/askhome/modera/1__thumb.webp";
import thumb161 from "@/assets/askhome/astra-prime/1__thumb.webp";
import thumb162 from "@/assets/karkas-dom-yug/shale-67/1__thumb.webp";
import thumb163 from "@/assets/karkas-dom-yug/shale-69/1__thumb.webp";
import thumb164 from "@/assets/karkas-dom-yug/shale-65/1__thumb.webp";
import thumb165 from "@/assets/karkas-dom-yug/shale-82/1__thumb.webp";
import thumb166 from "@/assets/karkas-dom-yug/shale-90/1__thumb.webp";
import thumb167 from "@/assets/sibiryak/barn-28/1__thumb.webp";
import thumb168 from "@/assets/sibiryak/barn-41/1__thumb.webp";
import thumb169 from "@/assets/sibiryak/barn-47/1__thumb.webp";
import thumb170 from "@/assets/sibiryak/barn-95/1__thumb.webp";
import thumb171 from "@/assets/sibiryak/barn-120/1__thumb.webp";
import thumb172 from "@/assets/doma-ot-mihalycha/kulibin/1__thumb.webp";
import thumb173 from "@/assets/doma-ot-mihalycha/lomonosov/1__thumb.webp";
import thumb174 from "@/assets/doma-ot-mihalycha/rakhmaninov/1__thumb.webp";
import thumb175 from "@/assets/doma-ot-mihalycha/derzhavin/1__thumb.webp";
import thumb176 from "@/assets/doma-ot-mihalycha/vinogradov/1__thumb.webp";
import thumb177 from "@/assets/barnstudio/opti/1__thumb.webp";
import thumb178 from "@/assets/barnstudio/adel/1__thumb.webp";
import thumb179 from "@/assets/barnstudio/alpina/1__thumb.webp";
import thumb180 from "@/assets/barnstudio/antresol/1__thumb.webp";
import thumb181 from "@/assets/barnstudio/vizhn/1__thumb.webp";
import thumb182 from "@/assets/beli-dom/valdaj/1__thumb.webp";
import thumb183 from "@/assets/beli-dom/semejnyj/1__thumb.webp";
import thumb184 from "@/assets/beli-dom/tradicziya/1__thumb.webp";
import thumb185 from "@/assets/beli-dom/karolina/1__thumb.webp";
import thumb186 from "@/assets/beli-dom/triumf/1__thumb.webp";
import thumb192 from "@/assets/mastergrupp-barnaul/angliya/01__thumb.webp";
import thumb193 from "@/assets/mastergrupp-barnaul/klavdiya/01__thumb.webp";
import thumb194 from "@/assets/mastergrupp-barnaul/vud/01__thumb.webp";
import thumb195 from "@/assets/mastergrupp-barnaul/briksiya/01__thumb.webp";
import thumb196 from "@/assets/mastergrupp-barnaul/burlakov/01__thumb.webp";
import thumb197 from "@/assets/azbuka/zarya-75x8/1__thumb.webp";
import thumb198 from "@/assets/azbuka/zarya-10x85/1__thumb.webp";
import thumb199 from "@/assets/azbuka/zarya-11x85/1__thumb.webp";
import thumb200 from "@/assets/azbuka/zarya-11x95/1__thumb.webp";
import thumb201 from "@/assets/azbuka/zarya-9x9/1__thumb.webp";
import thumb202 from "@/assets/rostdomik/krepost/1__thumb.webp";
import thumb203 from "@/assets/rostdomik/angel/1__thumb.webp";
import thumb204 from "@/assets/rostdomik/komfort-6x8/1__thumb.webp";
import thumb205 from "@/assets/rostdomik/zhemchuzhina-mini/1__thumb.webp";
import thumb206 from "@/assets/rostdomik/zhemchuzhina/1__thumb.webp";
import thumb207 from "@/assets/klyuch-st/dom-6x6/1__thumb.webp";
import thumb208 from "@/assets/klyuch-st/dom-6x9/1__thumb.webp";
import thumb209 from "@/assets/klyuch-st/dom-5x7/1__thumb.webp";
import thumb210 from "@/assets/klyuch-st/dom-6x8/1__thumb.webp";
import thumb211 from "@/assets/klyuch-st/dom-8x12/1__thumb.webp";
import thumb212 from "@/assets/doorhan/dom-29/1__thumb.webp";
import thumb213 from "@/assets/doorhan/dom-44/1__thumb.webp";
import thumb214 from "@/assets/doorhan/dom-59/1__thumb.webp";
import thumb215 from "@/assets/doorhan/dom-74/1__thumb.webp";
import thumb216 from "@/assets/doorhan/dom-88/1__thumb.webp";
import thumb217 from "@/assets/avgst/barn-75/1__thumb.webp";
import thumb218 from "@/assets/avgst/barn-134/1__thumb.webp";
import thumb219 from "@/assets/avgst/ekokhaus-124/1__thumb.webp";
import thumb220 from "@/assets/avgst/barn-74/1__thumb.webp";
import thumb221 from "@/assets/avgst/barn-73/1__thumb.webp";
import thumb222 from "@/assets/stroylider/kareliya-82/1__thumb.webp";
import thumb223 from "@/assets/stroylider/kareliya-81/1__thumb.webp";
import thumb224 from "@/assets/stroylider/kareliya-80/1__thumb.webp";
import thumb225 from "@/assets/stroylider/kareliya-75/1__thumb.webp";
import thumb226 from "@/assets/stroylider/kareliya-76/1__thumb.webp";
import thumb227 from "@/assets/postroidom/forest-91/1__thumb.webp";
import thumb228 from "@/assets/postroidom/forest-109/1__thumb.webp";
import thumb229 from "@/assets/postroidom/forest-137/1__thumb.webp";
import thumb230 from "@/assets/postroidom/forest-253/1__thumb.webp";
import thumb231 from "@/assets/postroidom/aframe-50/1__thumb.webp";
import thumb232 from "@/assets/altai-mda/oktyabr/1__thumb.webp";
import thumb233 from "@/assets/altai-mda/aya/1__thumb.webp";
import thumb234 from "@/assets/altai-mda/flora/1__thumb.webp";
import thumb235 from "@/assets/altai-mda/uznezya/1__thumb.webp";
import thumb236 from "@/assets/altai-mda/barantal/1__thumb.webp";
import thumb237 from "@/assets/praktika-stroy/ps-praktik-21-1__thumb.webp";
import thumb238 from "@/assets/praktika-stroy/ps-praktik-22-1__thumb.webp";
import thumb239 from "@/assets/praktika-stroy/ps-praktik-23-1__thumb.webp";
import thumb240 from "@/assets/praktika-stroy/ps-praktik-31-1__thumb.webp";
import thumb241 from "@/assets/praktika-stroy/ps-praktik-32-1__thumb.webp";
import thumb242 from "@/assets/eco-city/ec-mga-1__thumb.webp";
import thumb243 from "@/assets/eco-city/ec-dunay-1__thumb.webp";
import thumb244 from "@/assets/eco-city/ec-lammi-1__thumb.webp";
import thumb245 from "@/assets/eco-city/ec-imatra-1__thumb.webp";
import thumb246 from "@/assets/eco-city/ec-lahti-1__thumb.webp";
import thumb247 from "@/assets/modom/mo-uno-1__thumb.webp";
import thumb248 from "@/assets/modom/mo-o2-s-1__thumb.webp";
import thumb249 from "@/assets/modom/mo-o2-m-1__thumb.webp";
import thumb250 from "@/assets/modom/mo-o2-l-1__thumb.webp";
import thumb251 from "@/assets/modom/mo-o2-mini30-1__thumb.webp";
import thumb252 from "@/assets/housebox/hb-standart14-1__thumb.webp";
import thumb253 from "@/assets/housebox/hb-standart14m-1__thumb.webp";
import thumb254 from "@/assets/housebox/hb-standart19-1__thumb.webp";
import thumb255 from "@/assets/glavles/gl-8-35/01__thumb.webp";
import thumb256 from "@/assets/glavles/gl-8-27/01__thumb.webp";
import thumb257 from "@/assets/glavles/gl-8-25/01__thumb.webp";
import thumb258 from "@/assets/glavles/gl-8-68/01__thumb.webp";
import thumb259 from "@/assets/glavles/gl-8-87/01__thumb.webp";
import thumb260 from "@/assets/fps-modul/ah-281/01__thumb.webp";
import thumb261 from "@/assets/fps-modul/ah-313/01__thumb.webp";
import thumb262 from "@/assets/fps-modul/bh-411/01__thumb.webp";
import thumb263 from "@/assets/fps-modul/bh-412/01__thumb.webp";
import thumb264 from "@/assets/fps-modul/bh-403/01__thumb.webp";
import thumb265 from "@/assets/vek-trad/m-98/01__thumb.webp";
import thumb266 from "@/assets/vek-trad/m-85/01__thumb.webp";
import thumb267 from "@/assets/vek-trad/m-73/01__thumb.webp";
import thumb268 from "@/assets/vek-trad/m-60/01__thumb.webp";
import thumb269 from "@/assets/budushiy-dom/hitech-45/01__thumb.webp";
import thumb270 from "@/assets/budushiy-dom/hitech-36/01__thumb.webp";
import thumb271 from "@/assets/budushiy-dom/barn-60f/01__thumb.webp";
import thumb272 from "@/assets/budushiy-dom/dom-8/01__thumb.webp";
import thumb273 from "@/assets/budushiy-dom/modual-75/01__thumb.webp";

export const projectThumbs: Record<number, string> = {
  32: thumb32,
  33: thumb33,
  34: thumb34,
  35: thumb35,
  36: thumb36,
  40: thumb40,
  41: thumb41,
  42: thumb42,
  43: thumb43,
  44: thumb44,
  45: thumb45,
  46: thumb46,
  47: thumb47,
  48: thumb48,
  49: thumb49,
  50: thumb50,
  51: thumb51,
  52: thumb52,
  53: thumb53,
  54: thumb54,
  55: thumb55,
  56: thumb56,
  57: thumb57,
  58: thumb58,
  59: thumb59,
  60: thumb60,
  61: thumb61,
  62: thumb62,
  63: thumb63,
  64: thumb64,
  65: thumb65,
  66: thumb66,
  67: thumb67,
  68: thumb68,
  69: thumb69,
  70: thumb70,
  71: thumb71,
  72: thumb72,
  73: thumb73,
  74: thumb74,
  75: thumb75,
  76: thumb76,
  77: thumb77,
  78: thumb78,
  79: thumb79,
  80: thumb80,
  81: thumb81,
  82: thumb82,
  83: thumb83,
  84: thumb84,
  85: thumb85,
  86: thumb86,
  87: thumb87,
  88: thumb88,
  89: thumb89,
  90: thumb90,
  91: thumb91,
  92: thumb92,
  93: thumb93,
  94: thumb94,
  95: thumb95,
  96: thumb96,
  97: thumb97,
  98: thumb98,
  99: thumb99,
  100: thumb100,
  101: thumb101,
  102: thumb102,
  103: thumb103,
  104: thumb104,
  105: thumb105,
  106: thumb106,
  107: thumb107,
  108: thumb108,
  109: thumb109,
  110: thumb110,
  111: thumb111,
  112: thumb112,
  113: thumb113,
  114: thumb114,
  115: thumb115,
  116: thumb116,
  117: thumb117,
  118: thumb118,
  119: thumb119,
  120: thumb120,
  121: thumb121,
  122: thumb122,
  123: thumb123,
  124: thumb124,
  125: thumb125,
  126: thumb126,
  127: thumb127,
  128: thumb128,
  129: thumb129,
  130: thumb130,
  131: thumb131,
  132: thumb132,
  133: thumb133,
  134: thumb134,
  135: thumb135,
  136: thumb136,
  137: thumb137,
  138: thumb138,
  139: thumb139,
  140: thumb140,
  141: thumb141,
  142: thumb142,
  143: thumb143,
  144: thumb144,
  145: thumb145,
  146: thumb146,
  147: thumb147,
  148: thumb148,
  149: thumb149,
  150: thumb150,
  151: thumb151,
  152: thumb152,
  153: thumb153,
  154: thumb154,
  155: thumb155,
  156: thumb156,
  157: thumb157,
  158: thumb158,
  159: thumb159,
  160: thumb160,
  161: thumb161,
  162: thumb162,
  163: thumb163,
  164: thumb164,
  165: thumb165,
  166: thumb166,
  167: thumb167,
  168: thumb168,
  169: thumb169,
  170: thumb170,
  171: thumb171,
  172: thumb172,
  173: thumb173,
  174: thumb174,
  175: thumb175,
  176: thumb176,
  177: thumb177,
  178: thumb178,
  179: thumb179,
  180: thumb180,
  181: thumb181,
  182: thumb182,
  183: thumb183,
  184: thumb184,
  185: thumb185,
  186: thumb186,
  192: thumb192,
  193: thumb193,
  194: thumb194,
  195: thumb195,
  196: thumb196,
  197: thumb197,
  198: thumb198,
  199: thumb199,
  200: thumb200,
  201: thumb201,
  202: thumb202,
  203: thumb203,
  204: thumb204,
  205: thumb205,
  206: thumb206,
  207: thumb207,
  208: thumb208,
  209: thumb209,
  210: thumb210,
  211: thumb211,
  212: thumb212,
  213: thumb213,
  214: thumb214,
  215: thumb215,
  216: thumb216,
  217: thumb217,
  218: thumb218,
  219: thumb219,
  220: thumb220,
  221: thumb221,
  222: thumb222,
  223: thumb223,
  224: thumb224,
  225: thumb225,
  226: thumb226,
  227: thumb227,
  228: thumb228,
  229: thumb229,
  230: thumb230,
  231: thumb231,
  232: thumb232,
  233: thumb233,
  234: thumb234,
  235: thumb235,
  236: thumb236,
  237: thumb237,
  238: thumb238,
  239: thumb239,
  240: thumb240,
  241: thumb241,
  242: thumb242,
  243: thumb243,
  244: thumb244,
  245: thumb245,
  246: thumb246,
  247: thumb247,
  248: thumb248,
  249: thumb249,
  250: thumb250,
  251: thumb251,
  252: thumb252,
  253: thumb253,
  254: thumb254,
  255: thumb255,
  256: thumb256,
  257: thumb257,
  258: thumb258,
  259: thumb259,
  260: thumb260,
  261: thumb261,
  262: thumb262,
  263: thumb263,
  264: thumb264,
  265: thumb265,
  266: thumb266,
  267: thumb267,
  268: thumb268,
  269: thumb269,
  270: thumb270,
  271: thumb271,
  272: thumb272,
  273: thumb273,
};
