// Auto-generated by scripts/generate-card-thumbnails.mjs.
// Maps project id to the lightweight first image used in project cards.

import thumb31 from "@/assets/wide-house-1__thumb.webp";
import thumb33 from "@/assets/cabin-31-1__thumb.webp";
import thumb34 from "@/assets/bear-1__thumb.webp";
import thumb35 from "@/assets/bear77-1__thumb.webp";
import thumb36 from "@/assets/bear86-1__thumb.webp";
import thumb37 from "@/assets/bear134-1__thumb.webp";
import thumb38 from "@/assets/vast140-1__thumb.webp";
import thumb39 from "@/assets/bear168-1__thumb.webp";
import thumb40 from "@/assets/patio-6__thumb.webp";
import thumb41 from "@/assets/tundra-1__thumb.webp";
import thumb42 from "@/assets/sherwood-1__thumb.webp";
import thumb43 from "@/assets/senat-3__thumb.webp";
import thumb44 from "@/assets/family-suite-1__thumb.webp";
import thumb45 from "@/assets/gallant-1__thumb.webp";
import thumb46 from "@/assets/grandis-1__thumb.webp";
import thumb47 from "@/assets/glezman/larus-45__thumb.webp";
import thumb48 from "@/assets/glezman/larus-75__thumb.webp";
import thumb49 from "@/assets/glezman/larus-100__thumb.webp";
import thumb50 from "@/assets/glezman/larus-120__thumb.webp";
import thumb51 from "@/assets/glezman/larus-127__thumb.webp";
import thumb52 from "@/assets/divodom/start-30/1__thumb.webp";
import thumb53 from "@/assets/divodom/divo-34/1__thumb.webp";
import thumb54 from "@/assets/divodom/divo-51/1__thumb.webp";
import thumb55 from "@/assets/divodom/divo-64/1__thumb.webp";
import thumb56 from "@/assets/divodom/divo-88/1__thumb.webp";
import thumb57 from "@/assets/gradodom/filip-55-1__thumb.webp";
import thumb58 from "@/assets/gradodom/arktur-56-1__thumb.webp";
import thumb59 from "@/assets/gradodom/rinho-60-1__thumb.webp";
import thumb60 from "@/assets/gradodom/almaks-72-1__thumb.webp";
import thumb61 from "@/assets/gradodom/alester-73-1__thumb.webp";
import thumb62 from "@/assets/zagorodom/soul-1__thumb.webp";
import thumb63 from "@/assets/zagorodom/strong-1__thumb.webp";
import thumb64 from "@/assets/zagorodom/lumo-1__thumb.webp";
import thumb65 from "@/assets/zagorodom/happy-1__thumb.webp";
import thumb66 from "@/assets/zagorodom/favorite-1__thumb.webp";
import thumb67 from "@/assets/apa/aa-1/1__thumb.webp";
import thumb68 from "@/assets/apa/aa-2/1__thumb.webp";
import thumb69 from "@/assets/apa/aa-3/1__thumb.webp";
import thumb70 from "@/assets/apa/aa-4/1__thumb.webp";
import thumb71 from "@/assets/apa/aa-5/1__thumb.webp";
import thumb72 from "@/assets/prime-modul/barnhaus-200-2-etazha/1__thumb.webp";
import thumb73 from "@/assets/prime-modul/skandinaviya-72/1__thumb.webp";
import thumb74 from "@/assets/prime-modul/barn-42/1__thumb.webp";
import thumb75 from "@/assets/prime-modul/modern-72/1__thumb.webp";
import thumb76 from "@/assets/prime-modul/kantri-110/1__thumb.webp";
import thumb77 from "@/assets/utkino/lesnoy-32-1__thumb.webp";
import thumb78 from "@/assets/utkino/tikhiy-bereg-43-1__thumb.webp";
import thumb79 from "@/assets/utkino/bereginya-50-1__thumb.webp";
import thumb80 from "@/assets/utkino/berendey-63-1__thumb.webp";
import thumb81 from "@/assets/utkino/svetlitsa-prikamya-72-1__thumb.webp";
import thumb82 from "@/assets/teplodina/dk-122-1__thumb.webp";
import thumb83 from "@/assets/teplodina/dk-55-1__thumb.webp";
import thumb84 from "@/assets/teplodina/dk-67-1__thumb.webp";
import thumb85 from "@/assets/teplodina/dk-72-1__thumb.webp";
import thumb86 from "@/assets/teplodina/skandinaviya-1__thumb.webp";
import thumb87 from "@/assets/karkas-haus/kh-22-05/1__thumb.webp";
import thumb88 from "@/assets/karkas-haus/kh-23-10-barnhaus/1__thumb.webp";
import thumb89 from "@/assets/karkas-haus/kh-23-15-1/1__thumb.webp";
import thumb90 from "@/assets/karkas-haus/kh-23-15-2/1__thumb.webp";
import thumb91 from "@/assets/karkas-haus/kh-23-22-2/1__thumb.webp";
import thumb92 from "@/assets/ural-house/uh-skandi-120/1__thumb.webp";
import thumb93 from "@/assets/ural-house/uh-barn-92/1__thumb.webp";
import thumb94 from "@/assets/ural-house/uh-klassik-170/1__thumb.webp";
import thumb95 from "@/assets/ural-house/uh-fahverk-190/1__thumb.webp";
import thumb96 from "@/assets/ural-house/uh-klassik-76/1__thumb.webp";
import thumb97 from "@/assets/hochu-dom/dk-443-130/1__thumb.webp";
import thumb98 from "@/assets/hochu-dom/dk-387-115/1__thumb.webp";
import thumb99 from "@/assets/hochu-dom/dk-384-91/1__thumb.webp";
import thumb100 from "@/assets/hochu-dom/dk-428-127/1__thumb.webp";
import thumb101 from "@/assets/hochu-dom/dk-390-96/1__thumb.webp";
import thumb102 from "@/assets/scandiecodom/kd-1600/1__thumb.webp";
import thumb103 from "@/assets/scandiecodom/kd-1590/1__thumb.webp";
import thumb104 from "@/assets/scandiecodom/kd-1580/1__thumb.webp";
import thumb105 from "@/assets/scandiecodom/kd-1570/1__thumb.webp";
import thumb106 from "@/assets/scandiecodom/kd-1560/1__thumb.webp";
import thumb107 from "@/assets/karkas-povolzhya/madrid-3/1__thumb.webp";
import thumb108 from "@/assets/karkas-povolzhya/manchester/1__thumb.webp";
import thumb109 from "@/assets/karkas-povolzhya/stokgolm/1__thumb.webp";
import thumb110 from "@/assets/karkas-povolzhya/berlin/1__thumb.webp";
import thumb111 from "@/assets/karkas-povolzhya/london-1/1__thumb.webp";
import thumb112 from "@/assets/domoteka/glemping-barnhaus-6x7/1__thumb.webp";
import thumb113 from "@/assets/domoteka/parizh/1__thumb.webp";
import thumb114 from "@/assets/domoteka/elbrus/1__thumb.webp";
import thumb115 from "@/assets/domoteka/glemping-a-frame-6x6/1__thumb.webp";
import thumb116 from "@/assets/domoteka/fisht/1__thumb.webp";
import thumb117 from "@/assets/svoi-house/svoy-199/1__thumb.webp";
import thumb118 from "@/assets/svoi-house/svoy-layt-001/1__thumb.webp";
import thumb119 from "@/assets/svoi-house/svoy-100/1__thumb.webp";
import thumb120 from "@/assets/svoi-house/svoy-layt-004/1__thumb.webp";
import thumb121 from "@/assets/svoi-house/svoy-102-m/1__thumb.webp";
import thumb122 from "@/assets/bagrovstroy/9h15-dionis/1__thumb.webp";
import thumb123 from "@/assets/bagrovstroy/9h15-sadko/1__thumb.webp";
import thumb124 from "@/assets/bagrovstroy/10-5h11-avgust/1__thumb.webp";
import thumb125 from "@/assets/bagrovstroy/6h8-saveliy/1__thumb.webp";
import thumb126 from "@/assets/bagrovstroy/7h9-gostimir/1__thumb.webp";
import thumb127 from "@/assets/domakarkas/kd-120/1__thumb.webp";
import thumb128 from "@/assets/domakarkas/kd-119/1__thumb.webp";
import thumb129 from "@/assets/domakarkas/kd-118/1__thumb.webp";
import thumb130 from "@/assets/domakarkas/kd-117/1__thumb.webp";
import thumb131 from "@/assets/domakarkas/kd-116/1__thumb.webp";
import thumb132 from "@/assets/sk-garmoniya/vyazma/1__thumb.webp";
import thumb133 from "@/assets/sk-garmoniya/sosnovyy-bor/1__thumb.webp";
import thumb134 from "@/assets/sk-garmoniya/troitsk/1__thumb.webp";
import thumb135 from "@/assets/sk-garmoniya/vyborg/1__thumb.webp";
import thumb136 from "@/assets/sk-garmoniya/samara/1__thumb.webp";
import thumb137 from "@/assets/berest-dom/bogatyr-lk-7h9/1__thumb.webp";
import thumb138 from "@/assets/berest-dom/kareliya-2-7h9/1__thumb.webp";
import thumb139 from "@/assets/berest-dom/senator-7-5h9/1__thumb.webp";
import thumb140 from "@/assets/berest-dom/kareliya-1-7h8/1__thumb.webp";
import thumb141 from "@/assets/berest-dom/senator-2-8-5h10-5/1__thumb.webp";
import thumb142 from "@/assets/rift/dg51/1__thumb.webp";
import thumb143 from "@/assets/rift/dg50/1__thumb.webp";
import thumb144 from "@/assets/rift/xx27/1__thumb.webp";
import thumb145 from "@/assets/rift/dg49/1__thumb.webp";
import thumb146 from "@/assets/rift/xx05/1__thumb.webp";
import thumb147 from "@/assets/izbrusa/kd-38/1__thumb.webp";
import thumb148 from "@/assets/izbrusa/kd-29/1__thumb.webp";
import thumb149 from "@/assets/izbrusa/kd-41/1__thumb.webp";
import thumb150 from "@/assets/izbrusa/kd-12/1__thumb.webp";
import thumb151 from "@/assets/izbrusa/kd-36/1__thumb.webp";
import thumb152 from "@/assets/kazanstroy16/bigl/1__thumb.webp";
import thumb153 from "@/assets/kazanstroy16/diotima/1__thumb.webp";
import thumb154 from "@/assets/kazanstroy16/glenapp/1__thumb.webp";
import thumb155 from "@/assets/kazanstroy16/strakeya/1__thumb.webp";
import thumb156 from "@/assets/kazanstroy16/izabella/1__thumb.webp";
import thumb157 from "@/assets/askhome/nova-prime/1__thumb.webp";
import thumb158 from "@/assets/askhome/nova/1__thumb.webp";
import thumb159 from "@/assets/askhome/modera-prime/1__thumb.webp";
import thumb160 from "@/assets/askhome/modera/1__thumb.webp";
import thumb161 from "@/assets/askhome/astra-prime/1__thumb.webp";
import thumb162 from "@/assets/karkas-dom-yug/shale-67/1__thumb.webp";
import thumb163 from "@/assets/karkas-dom-yug/shale-69/1__thumb.webp";
import thumb164 from "@/assets/karkas-dom-yug/shale-65/1__thumb.webp";
import thumb165 from "@/assets/karkas-dom-yug/shale-82/1__thumb.webp";
import thumb166 from "@/assets/karkas-dom-yug/shale-90/1__thumb.webp";
import thumb167 from "@/assets/sibiryak/barn-28/1__thumb.webp";
import thumb168 from "@/assets/sibiryak/barn-41/1__thumb.webp";
import thumb169 from "@/assets/sibiryak/barn-47/1__thumb.webp";
import thumb170 from "@/assets/sibiryak/barn-95/1__thumb.webp";
import thumb171 from "@/assets/sibiryak/barn-120/1__thumb.webp";
import thumb172 from "@/assets/doma-ot-mihalycha/kulibin/1__thumb.webp";
import thumb173 from "@/assets/doma-ot-mihalycha/lomonosov/1__thumb.webp";
import thumb174 from "@/assets/doma-ot-mihalycha/rakhmaninov/1__thumb.webp";
import thumb175 from "@/assets/doma-ot-mihalycha/derzhavin/1__thumb.webp";
import thumb176 from "@/assets/doma-ot-mihalycha/vinogradov/1__thumb.webp";
import thumb177 from "@/assets/barnstudio/opti/1__thumb.webp";
import thumb178 from "@/assets/barnstudio/adel/1__thumb.webp";
import thumb179 from "@/assets/barnstudio/alpina/1__thumb.webp";
import thumb180 from "@/assets/barnstudio/antresol/1__thumb.webp";
import thumb181 from "@/assets/barnstudio/vizhn/1__thumb.webp";
import thumb182 from "@/assets/beli-dom/valdaj/1__thumb.webp";
import thumb183 from "@/assets/beli-dom/semejnyj/1__thumb.webp";
import thumb184 from "@/assets/beli-dom/tradicziya/1__thumb.webp";
import thumb185 from "@/assets/beli-dom/karolina/1__thumb.webp";
import thumb186 from "@/assets/beli-dom/triumf/1__thumb.webp";
import thumb192 from "@/assets/mastergrupp-barnaul/angliya/01__thumb.webp";
import thumb193 from "@/assets/mastergrupp-barnaul/klavdiya/01__thumb.webp";
import thumb194 from "@/assets/mastergrupp-barnaul/vud/01__thumb.webp";
import thumb195 from "@/assets/mastergrupp-barnaul/briksiya/01__thumb.webp";
import thumb196 from "@/assets/mastergrupp-barnaul/burlakov/01__thumb.webp";
import thumb197 from "@/assets/azbuka/zarya-75x8/1__thumb.webp";
import thumb198 from "@/assets/azbuka/zarya-10x85/1__thumb.webp";
import thumb199 from "@/assets/azbuka/zarya-11x85/1__thumb.webp";
import thumb200 from "@/assets/azbuka/zarya-11x95/1__thumb.webp";
import thumb201 from "@/assets/azbuka/zarya-9x9/1__thumb.webp";
import thumb202 from "@/assets/rostdomik/krepost/1__thumb.webp";
import thumb203 from "@/assets/rostdomik/angel/1__thumb.webp";
import thumb204 from "@/assets/rostdomik/komfort-6x8/1__thumb.webp";
import thumb205 from "@/assets/rostdomik/zhemchuzhina-mini/1__thumb.webp";
import thumb206 from "@/assets/rostdomik/zhemchuzhina/1__thumb.webp";
import thumb207 from "@/assets/klyuch-st/dom-6x6/1__thumb.webp";
import thumb208 from "@/assets/klyuch-st/dom-6x9/1__thumb.webp";
import thumb209 from "@/assets/klyuch-st/dom-5x7/1__thumb.webp";
import thumb210 from "@/assets/klyuch-st/dom-6x8/1__thumb.webp";
import thumb211 from "@/assets/klyuch-st/dom-8x12/1__thumb.webp";
import thumb212 from "@/assets/doorhan/dom-29/1__thumb.webp";
import thumb213 from "@/assets/doorhan/dom-44/1__thumb.webp";
import thumb214 from "@/assets/doorhan/dom-59/1__thumb.webp";
import thumb215 from "@/assets/doorhan/dom-74/1__thumb.webp";
import thumb216 from "@/assets/doorhan/dom-88/1__thumb.webp";
import thumb217 from "@/assets/avgst/barn-75/1__thumb.webp";
import thumb218 from "@/assets/avgst/barn-134/1__thumb.webp";
import thumb219 from "@/assets/avgst/ekokhaus-124/1__thumb.webp";
import thumb220 from "@/assets/avgst/barn-74/1__thumb.webp";
import thumb221 from "@/assets/avgst/barn-73/1__thumb.webp";
import thumb222 from "@/assets/stroylider/kareliya-82/1__thumb.webp";
import thumb223 from "@/assets/stroylider/kareliya-81/1__thumb.webp";
import thumb224 from "@/assets/stroylider/kareliya-80/1__thumb.webp";
import thumb225 from "@/assets/stroylider/kareliya-75/1__thumb.webp";
import thumb226 from "@/assets/stroylider/kareliya-76/1__thumb.webp";
import thumb227 from "@/assets/postroidom/forest-91/1__thumb.webp";
import thumb228 from "@/assets/postroidom/forest-109/1__thumb.webp";
import thumb229 from "@/assets/postroidom/forest-137/1__thumb.webp";
import thumb230 from "@/assets/postroidom/forest-253/1__thumb.webp";
import thumb231 from "@/assets/postroidom/aframe-50/1__thumb.webp";
import thumb232 from "@/assets/altai-mda/oktyabr/1__thumb.webp";
import thumb233 from "@/assets/altai-mda/aya/1__thumb.webp";
import thumb234 from "@/assets/altai-mda/flora/1__thumb.webp";
import thumb235 from "@/assets/altai-mda/uznezya/1__thumb.webp";
import thumb236 from "@/assets/altai-mda/barantal/1__thumb.webp";
import thumb237 from "@/assets/praktika-stroy/ps-praktik-21-1__thumb.webp";
import thumb238 from "@/assets/praktika-stroy/ps-praktik-22-1__thumb.webp";
import thumb239 from "@/assets/praktika-stroy/ps-praktik-23-1__thumb.webp";
import thumb240 from "@/assets/praktika-stroy/ps-praktik-31-1__thumb.webp";
import thumb241 from "@/assets/praktika-stroy/ps-praktik-32-1__thumb.webp";
import thumb242 from "@/assets/eco-city/ec-mga-1__thumb.webp";
import thumb243 from "@/assets/eco-city/ec-dunay-1__thumb.webp";
import thumb244 from "@/assets/eco-city/ec-lammi-1__thumb.webp";
import thumb245 from "@/assets/eco-city/ec-imatra-1__thumb.webp";
import thumb246 from "@/assets/eco-city/ec-lahti-1__thumb.webp";
import thumb247 from "@/assets/modom/mo-uno-1__thumb.webp";
import thumb248 from "@/assets/modom/mo-o2-s-1__thumb.webp";
import thumb249 from "@/assets/modom/mo-o2-m-1__thumb.webp";
import thumb250 from "@/assets/modom/mo-o2-l-1__thumb.webp";
import thumb251 from "@/assets/modom/mo-o2-mini30-1__thumb.webp";
import thumb252 from "@/assets/housebox/hb-standart14-1__thumb.webp";
import thumb253 from "@/assets/housebox/hb-standart14m-1__thumb.webp";
import thumb254 from "@/assets/housebox/hb-standart19-1__thumb.webp";
import thumb255 from "@/assets/glavles/gl-8-35/01__thumb.webp";
import thumb256 from "@/assets/glavles/gl-8-27/01__thumb.webp";
import thumb257 from "@/assets/glavles/gl-8-25/01__thumb.webp";
import thumb258 from "@/assets/glavles/gl-8-68/01__thumb.webp";
import thumb259 from "@/assets/glavles/gl-8-87/01__thumb.webp";
import thumb260 from "@/assets/fps-modul/ah-281/01__thumb.webp";
import thumb261 from "@/assets/fps-modul/ah-313/01__thumb.webp";
import thumb262 from "@/assets/fps-modul/bh-411/01__thumb.webp";
import thumb263 from "@/assets/fps-modul/bh-412/01__thumb.webp";
import thumb264 from "@/assets/fps-modul/bh-403/01__thumb.webp";
import thumb265 from "@/assets/vek-trad/m-98/01__thumb.webp";
import thumb266 from "@/assets/vek-trad/m-85/01__thumb.webp";
import thumb267 from "@/assets/vek-trad/m-73/01__thumb.webp";
import thumb268 from "@/assets/vek-trad/m-60/01__thumb.webp";
import thumb269 from "@/assets/budushiy-dom/hitech-45/01__thumb.webp";
import thumb270 from "@/assets/budushiy-dom/hitech-36/01__thumb.webp";
import thumb271 from "@/assets/budushiy-dom/barn-60f/01__thumb.webp";
import thumb272 from "@/assets/budushiy-dom/dom-8/01__thumb.webp";
import thumb273 from "@/assets/budushiy-dom/modual-75/01__thumb.webp";
import thumb274 from "@/assets/qubdom/q/01__thumb.webp";
import thumb275 from "@/assets/qubdom/q-plus/01__thumb.webp";
import thumb276 from "@/assets/qubdom/q-family-mini/01__thumb.webp";
import thumb277 from "@/assets/qubdom/q-family-max/01__thumb.webp";
import thumb278 from "@/assets/qubdom/q-s-tamburom/01__thumb.webp";
import thumb279 from "@/assets/durov-house/barn-dh21/01__thumb.webp";
import thumb280 from "@/assets/durov-house/barn-dh57/01__thumb.webp";
import thumb281 from "@/assets/durov-house/barn-dh64/01__thumb.webp";
import thumb282 from "@/assets/durov-house/flat-dh67/01__thumb.webp";
import thumb283 from "@/assets/durov-house/flat-dh124/01__thumb.webp";
import thumb284 from "@/assets/histhut/hizhina-8/01__thumb.webp";
import thumb285 from "@/assets/histhut/hizhina-10/01__thumb.webp";
import thumb286 from "@/assets/histhut/hizhina-12/01__thumb.webp";
import thumb287 from "@/assets/histhut/hizhina-20/01__thumb.webp";
import thumb288 from "@/assets/histhut/hizhina-25/01__thumb.webp";
import thumb294 from "@/assets/countryhouse/hitech-m1/01__thumb.webp";
import thumb295 from "@/assets/countryhouse/hitech-m15/01__thumb.webp";
import thumb296 from "@/assets/countryhouse/hitech-m2/01__thumb.webp";
import thumb297 from "@/assets/countryhouse/hitech-m3/01__thumb.webp";
import thumb298 from "@/assets/countryhouse/hitech-m5/01__thumb.webp";
import thumb299 from "@/assets/cubadom/cuba-35-1/01__thumb.webp";
import thumb300 from "@/assets/cubadom/cuba-35-2/01__thumb.webp";
import thumb301 from "@/assets/cubadom/cuba-53-1/01__thumb.webp";
import thumb302 from "@/assets/cubadom/cuba-53-2/01__thumb.webp";
import thumb303 from "@/assets/cubadom/cuba-70-1/01__thumb.webp";
import thumb304 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-36/01__thumb.webp";
import thumb305 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-47/01__thumb.webp";
import thumb306 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-62/01__thumb.webp";
import thumb307 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-72/01__thumb.webp";
import thumb308 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-86/01__thumb.webp";
import thumb309 from "@/assets/woodalp/woodhouse-60-pro/01__thumb.webp";
import thumb310 from "@/assets/woodalp/woodhouse-90-pro/01__thumb.webp";
import thumb311 from "@/assets/woodalp/woodhouse-120-pro/01__thumb.webp";
import thumb312 from "@/assets/boxmate/flat-5-box/01__thumb.webp";
import thumb313 from "@/assets/boxmate/flat-4-box/01__thumb.webp";
import thumb314 from "@/assets/boxmate/flat-3-box/01__thumb.webp";
import thumb315 from "@/assets/boxmate/red-5-box/01__thumb.webp";
import thumb316 from "@/assets/boxmate/red-4-box/01__thumb.webp";
import thumb317 from "@/assets/uvhouse/mono-30/01__thumb.webp";
import thumb318 from "@/assets/uvhouse/skandi-32/01__thumb.webp";
import thumb319 from "@/assets/uvhouse/nord-40/01__thumb.webp";
import thumb320 from "@/assets/uvhouse/shale-24/01__thumb.webp";
import thumb321 from "@/assets/uvhouse/skandi-40/01__thumb.webp";
import thumb322 from "@/assets/asterius/altair-20/01__thumb.webp";
import thumb323 from "@/assets/asterius/altair-30/01__thumb.webp";
import thumb324 from "@/assets/asterius/antares-40/01__thumb.webp";
import thumb325 from "@/assets/asterius/antares-60/01__thumb.webp";
import thumb326 from "@/assets/asterius/antares-80/01__thumb.webp";
import thumb327 from "@/assets/smola/smola-103/01__thumb.webp";
import thumb328 from "@/assets/smola/smola-65/01__thumb.webp";
import thumb329 from "@/assets/smola/smola-77/01__thumb.webp";
import thumb330 from "@/assets/smola/smola-43/01__thumb.webp";
import thumb331 from "@/assets/ultradomspb/ultra-36/01__thumb.webp";
import thumb332 from "@/assets/ultradomspb/ultra-54/01__thumb.webp";
import thumb333 from "@/assets/ultradomspb/ultra-72/01__thumb.webp";
import thumb334 from "@/assets/ultradomspb/ultra-65/01__thumb.webp";
import thumb335 from "@/assets/ultradomspb/ultra-85/01__thumb.webp";
import thumb336 from "@/assets/freedom/naturi-55/01__thumb.webp";
import thumb337 from "@/assets/freedom/naturi-100/01__thumb.webp";
import thumb338 from "@/assets/freedom/freedom-barn/01__thumb.webp";
import thumb339 from "@/assets/chebwood/modul-15/01__thumb.webp";
import thumb340 from "@/assets/chebwood/dom-pod-kluch/01__thumb.webp";
import thumb341 from "@/assets/chebwood/glamping/01__thumb.webp";
import thumb342 from "@/assets/campingdom/campingdom-15/01__thumb.webp";
import thumb343 from "@/assets/campingdom/campingdom-22/01__thumb.webp";
import thumb344 from "@/assets/campingdom/campingdom-32/01__thumb.webp";
import thumb345 from "@/assets/campingdom/campingdom-15-barn/01__thumb.webp";
import thumb346 from "@/assets/campingdom/campingdom-28-barn/01__thumb.webp";
import thumb347 from "@/assets/pslcomp/barn-36/01__thumb.webp";
import thumb348 from "@/assets/pslcomp/haytek-36/01__thumb.webp";
import thumb349 from "@/assets/pslcomp/barn-40/01__thumb.webp";
import thumb350 from "@/assets/pslcomp/haytek-40/01__thumb.webp";
import thumb351 from "@/assets/pslcomp/barn-45/01__thumb.webp";
import thumb352 from "@/assets/domnasm/domnas-35/01__thumb.webp";
import thumb353 from "@/assets/domnasm/domnas-50/01__thumb.webp";
import thumb354 from "@/assets/domnasm/domnas-80/01__thumb.webp";
import thumb355 from "@/assets/domnasm/barn/01__thumb.webp";
import thumb356 from "@/assets/domnasm/mgn/01__thumb.webp";
import thumb357 from "@/assets/blackmodule/one-module/01__thumb.webp";
import thumb358 from "@/assets/blackmodule/one-half-module/01__thumb.webp";
import thumb359 from "@/assets/blackmodule/two-module/01__thumb.webp";
import thumb360 from "@/assets/blackmodule/three-module/01__thumb.webp";
import thumb361 from "@/assets/blackmodule/four-module/01__thumb.webp";
import thumb362 from "@/assets/domm/modul-house-1/01__thumb.webp";
import thumb363 from "@/assets/domm/modul-house-2/01__thumb.webp";
import thumb364 from "@/assets/domm/modul-house-3/01__thumb.webp";
import thumb365 from "@/assets/domm/modul-house-4/01__thumb.webp";
import thumb366 from "@/assets/domm/modul-house-6/01__thumb.webp";
import thumb367 from "@/assets/my-module/barni/01__thumb.webp";
import thumb368 from "@/assets/my-module/korner/01__thumb.webp";
import thumb369 from "@/assets/my-module/scandinavia/01__thumb.webp";
import thumb370 from "@/assets/my-module/z/01__thumb.webp";
import thumb371 from "@/assets/4modul/karelia-30/01__thumb.webp";
import thumb372 from "@/assets/4modul/karelia-45/01__thumb.webp";
import thumb373 from "@/assets/4modul/karelia-60/01__thumb.webp";
import thumb374 from "@/assets/4modul/karelia-75/01__thumb.webp";
import thumb375 from "@/assets/4modul/barn-60/01__thumb.webp";
import thumb376 from "@/assets/cubber/house-48/01__thumb.webp";
import thumb377 from "@/assets/cubber/house-50/01__thumb.webp";
import thumb378 from "@/assets/cubber/house-60/01__thumb.webp";
import thumb379 from "@/assets/cubber/house-65/01__thumb.webp";
import thumb380 from "@/assets/cubber/house-95t/01__thumb.webp";
import thumb381 from "@/assets/simplehouse/simple-6/01__thumb.webp";
import thumb382 from "@/assets/panoramic-home/xl-54/01__thumb.webp";
import thumb383 from "@/assets/panoramic-home/max-87/01__thumb.webp";
import thumb384 from "@/assets/panoramic-home/xl-60/01__thumb.webp";
import thumb385 from "@/assets/panoramic-home/xl-72/01__thumb.webp";
import thumb386 from "@/assets/panoramic-home/xl-45/01__thumb.webp";
import thumb387 from "@/assets/ambarn/barn-40-lux/01__thumb.webp";
import thumb388 from "@/assets/ambarn/indigo-30/01__thumb.webp";
import thumb389 from "@/assets/ambarn/indigo-40/01__thumb.webp";
import thumb390 from "@/assets/ambarn/indigo-50/01__thumb.webp";
import thumb391 from "@/assets/ambarn/indigo-36/01__thumb.webp";
import thumb392 from "@/assets/myfamilyhouse/project-1/01__thumb.webp";
import thumb393 from "@/assets/myfamilyhouse/project-2/01__thumb.webp";
import thumb394 from "@/assets/myfamilyhouse/project-3/01__thumb.webp";
import thumb395 from "@/assets/myfamilyhouse/project-4/01__thumb.webp";
import thumb396 from "@/assets/myfamilyhouse/project-5/01__thumb.webp";
import thumb397 from "@/assets/stroygrad/quattro-barn/01__thumb.webp";
import thumb398 from "@/assets/stroygrad/sonin-lug/01__thumb.webp";
import thumb399 from "@/assets/stroygrad/minidom/01__thumb.webp";
import thumb400 from "@/assets/stroygrad/siete-offset/01__thumb.webp";
import thumb401 from "@/assets/stroygrad/double-barn/01__thumb.webp";
import thumb402 from "@/assets/modulcamp/barn-house/01__thumb.webp";
import thumb403 from "@/assets/modulcamp/gollandiya/01__thumb.webp";
import thumb404 from "@/assets/modulcamp/shale/01__thumb.webp";
import thumb405 from "@/assets/modulcamp/finlandiya/01__thumb.webp";
import thumb406 from "@/assets/modulcamp/daniya/01__thumb.webp";
import thumb407 from "@/assets/elmaco/ivor/01__thumb.webp";
import thumb408 from "@/assets/elmaco/lukas/01__thumb.webp";
import thumb409 from "@/assets/elmaco/jung/01__thumb.webp";
import thumb410 from "@/assets/elmaco/tor/01__thumb.webp";
import thumb411 from "@/assets/elmaco/oscar/01__thumb.webp";
import thumb412 from "@/assets/novator/radius/01__thumb.webp";
import thumb413 from "@/assets/novator/n3/01__thumb.webp";
import thumb414 from "@/assets/novator/n2/01__thumb.webp";
import thumb415 from "@/assets/novator/n1/01__thumb.webp";
import thumb416 from "@/assets/novator/n4/01__thumb.webp";
import thumb417 from "@/assets/blagohouse/blagobarn-29/01__thumb.webp";
import thumb418 from "@/assets/blagohouse/blagobarn-60/01__thumb.webp";
import thumb419 from "@/assets/blagohouse/blagobarn-65/01__thumb.webp";
import thumb420 from "@/assets/blagohouse/blagobarn-103/01__thumb.webp";
import thumb421 from "@/assets/blagohouse/blagobarn-41/01__thumb.webp";
import thumb422 from "@/assets/stilnye-moduli/double-s/01__thumb.webp";
import thumb423 from "@/assets/stilnye-moduli/double-xs-terrace/01__thumb.webp";
import thumb424 from "@/assets/stilnye-moduli/barnhaus-double/01__thumb.webp";
import thumb425 from "@/assets/stilnye-moduli/triple-s-terrace/01__thumb.webp";
import thumb426 from "@/assets/stilnye-moduli/quad/01__thumb.webp";
import thumb427 from "@/assets/ip-modul/ip-40/01__thumb.webp";
import thumb428 from "@/assets/ip-modul/ip-48/01__thumb.webp";
import thumb429 from "@/assets/ip-modul/ip-60/01__thumb.webp";
import thumb430 from "@/assets/ip-modul/ip-64/01__thumb.webp";
import thumb431 from "@/assets/ip-modul/ip-72/01__thumb.webp";
import thumb432 from "@/assets/rusmodul-spb/atreum-21/01__thumb.webp";
import thumb433 from "@/assets/rusmodul-spb/atreum-28/01__thumb.webp";
import thumb434 from "@/assets/rusmodul-spb/lodge-30/01__thumb.webp";
import thumb435 from "@/assets/rusmodul-spb/double-lodge-50/01__thumb.webp";
import thumb436 from "@/assets/rusmodul-spb/scandic-double-60/01__thumb.webp";
import thumb437 from "@/assets/platforma-baths/bathhouse-01__thumb.webp";
import thumb438 from "@/assets/platforma-baths/bathhouse-spa-01__thumb.webp";
import mobileThumb31 from "@/assets/wide-house-1__thumb_mobile.avif";
import mobileThumb33 from "@/assets/cabin-31-1__thumb_mobile.avif";
import mobileThumb34 from "@/assets/bear-1__thumb_mobile.avif";
import mobileThumb35 from "@/assets/bear77-1__thumb_mobile.avif";
import mobileThumb36 from "@/assets/bear86-1__thumb_mobile.avif";
import mobileThumb37 from "@/assets/bear134-1__thumb_mobile.avif";
import mobileThumb38 from "@/assets/vast140-1__thumb_mobile.avif";
import mobileThumb39 from "@/assets/bear168-1__thumb_mobile.avif";
import mobileThumb40 from "@/assets/patio-6__thumb_mobile.avif";
import mobileThumb41 from "@/assets/tundra-1__thumb_mobile.avif";
import mobileThumb42 from "@/assets/sherwood-1__thumb_mobile.avif";
import mobileThumb43 from "@/assets/senat-3__thumb_mobile.avif";
import mobileThumb44 from "@/assets/family-suite-1__thumb_mobile.avif";
import mobileThumb45 from "@/assets/gallant-1__thumb_mobile.avif";
import mobileThumb46 from "@/assets/grandis-1__thumb_mobile.avif";
import mobileThumb47 from "@/assets/glezman/larus-45__thumb_mobile.avif";
import mobileThumb48 from "@/assets/glezman/larus-75__thumb_mobile.avif";
import mobileThumb49 from "@/assets/glezman/larus-100__thumb_mobile.avif";
import mobileThumb50 from "@/assets/glezman/larus-120__thumb_mobile.avif";
import mobileThumb51 from "@/assets/glezman/larus-127__thumb_mobile.avif";
import mobileThumb52 from "@/assets/divodom/start-30/1__thumb_mobile.avif";
import mobileThumb53 from "@/assets/divodom/divo-34/1__thumb_mobile.avif";
import mobileThumb54 from "@/assets/divodom/divo-51/1__thumb_mobile.avif";
import mobileThumb55 from "@/assets/divodom/divo-64/1__thumb_mobile.avif";
import mobileThumb56 from "@/assets/divodom/divo-88/1__thumb_mobile.avif";
import mobileThumb57 from "@/assets/gradodom/filip-55-1__thumb_mobile.avif";
import mobileThumb58 from "@/assets/gradodom/arktur-56-1__thumb_mobile.avif";
import mobileThumb59 from "@/assets/gradodom/rinho-60-1__thumb_mobile.avif";
import mobileThumb60 from "@/assets/gradodom/almaks-72-1__thumb_mobile.avif";
import mobileThumb61 from "@/assets/gradodom/alester-73-1__thumb_mobile.avif";
import mobileThumb62 from "@/assets/zagorodom/soul-1__thumb_mobile.avif";
import mobileThumb63 from "@/assets/zagorodom/strong-1__thumb_mobile.avif";
import mobileThumb64 from "@/assets/zagorodom/lumo-1__thumb_mobile.avif";
import mobileThumb65 from "@/assets/zagorodom/happy-1__thumb_mobile.avif";
import mobileThumb66 from "@/assets/zagorodom/favorite-1__thumb_mobile.avif";
import mobileThumb67 from "@/assets/apa/aa-1/1__thumb_mobile.avif";
import mobileThumb68 from "@/assets/apa/aa-2/1__thumb_mobile.avif";
import mobileThumb69 from "@/assets/apa/aa-3/1__thumb_mobile.avif";
import mobileThumb70 from "@/assets/apa/aa-4/1__thumb_mobile.avif";
import mobileThumb71 from "@/assets/apa/aa-5/1__thumb_mobile.avif";
import mobileThumb72 from "@/assets/prime-modul/barnhaus-200-2-etazha/1__thumb_mobile.avif";
import mobileThumb73 from "@/assets/prime-modul/skandinaviya-72/1__thumb_mobile.avif";
import mobileThumb74 from "@/assets/prime-modul/barn-42/1__thumb_mobile.avif";
import mobileThumb75 from "@/assets/prime-modul/modern-72/1__thumb_mobile.avif";
import mobileThumb76 from "@/assets/prime-modul/kantri-110/1__thumb_mobile.avif";
import mobileThumb77 from "@/assets/utkino/lesnoy-32-1__thumb_mobile.avif";
import mobileThumb78 from "@/assets/utkino/tikhiy-bereg-43-1__thumb_mobile.avif";
import mobileThumb79 from "@/assets/utkino/bereginya-50-1__thumb_mobile.avif";
import mobileThumb80 from "@/assets/utkino/berendey-63-1__thumb_mobile.avif";
import mobileThumb81 from "@/assets/utkino/svetlitsa-prikamya-72-1__thumb_mobile.avif";
import mobileThumb82 from "@/assets/teplodina/dk-122-1__thumb_mobile.avif";
import mobileThumb83 from "@/assets/teplodina/dk-55-1__thumb_mobile.avif";
import mobileThumb84 from "@/assets/teplodina/dk-67-1__thumb_mobile.avif";
import mobileThumb85 from "@/assets/teplodina/dk-72-1__thumb_mobile.avif";
import mobileThumb86 from "@/assets/teplodina/skandinaviya-1__thumb_mobile.avif";
import mobileThumb87 from "@/assets/karkas-haus/kh-22-05/1__thumb_mobile.avif";
import mobileThumb88 from "@/assets/karkas-haus/kh-23-10-barnhaus/1__thumb_mobile.avif";
import mobileThumb89 from "@/assets/karkas-haus/kh-23-15-1/1__thumb_mobile.avif";
import mobileThumb90 from "@/assets/karkas-haus/kh-23-15-2/1__thumb_mobile.avif";
import mobileThumb91 from "@/assets/karkas-haus/kh-23-22-2/1__thumb_mobile.avif";
import mobileThumb92 from "@/assets/ural-house/uh-skandi-120/1__thumb_mobile.avif";
import mobileThumb93 from "@/assets/ural-house/uh-barn-92/1__thumb_mobile.avif";
import mobileThumb94 from "@/assets/ural-house/uh-klassik-170/1__thumb_mobile.avif";
import mobileThumb95 from "@/assets/ural-house/uh-fahverk-190/1__thumb_mobile.avif";
import mobileThumb96 from "@/assets/ural-house/uh-klassik-76/1__thumb_mobile.avif";
import mobileThumb97 from "@/assets/hochu-dom/dk-443-130/1__thumb_mobile.avif";
import mobileThumb98 from "@/assets/hochu-dom/dk-387-115/1__thumb_mobile.avif";
import mobileThumb99 from "@/assets/hochu-dom/dk-384-91/1__thumb_mobile.avif";
import mobileThumb100 from "@/assets/hochu-dom/dk-428-127/1__thumb_mobile.avif";
import mobileThumb101 from "@/assets/hochu-dom/dk-390-96/1__thumb_mobile.avif";
import mobileThumb102 from "@/assets/scandiecodom/kd-1600/1__thumb_mobile.avif";
import mobileThumb103 from "@/assets/scandiecodom/kd-1590/1__thumb_mobile.avif";
import mobileThumb104 from "@/assets/scandiecodom/kd-1580/1__thumb_mobile.avif";
import mobileThumb105 from "@/assets/scandiecodom/kd-1570/1__thumb_mobile.avif";
import mobileThumb106 from "@/assets/scandiecodom/kd-1560/1__thumb_mobile.avif";
import mobileThumb107 from "@/assets/karkas-povolzhya/madrid-3/1__thumb_mobile.avif";
import mobileThumb108 from "@/assets/karkas-povolzhya/manchester/1__thumb_mobile.avif";
import mobileThumb109 from "@/assets/karkas-povolzhya/stokgolm/1__thumb_mobile.avif";
import mobileThumb110 from "@/assets/karkas-povolzhya/berlin/1__thumb_mobile.avif";
import mobileThumb111 from "@/assets/karkas-povolzhya/london-1/1__thumb_mobile.avif";
import mobileThumb112 from "@/assets/domoteka/glemping-barnhaus-6x7/1__thumb_mobile.avif";
import mobileThumb113 from "@/assets/domoteka/parizh/1__thumb_mobile.avif";
import mobileThumb114 from "@/assets/domoteka/elbrus/1__thumb_mobile.avif";
import mobileThumb115 from "@/assets/domoteka/glemping-a-frame-6x6/1__thumb_mobile.avif";
import mobileThumb116 from "@/assets/domoteka/fisht/1__thumb_mobile.avif";
import mobileThumb117 from "@/assets/svoi-house/svoy-199/1__thumb_mobile.avif";
import mobileThumb118 from "@/assets/svoi-house/svoy-layt-001/1__thumb_mobile.avif";
import mobileThumb119 from "@/assets/svoi-house/svoy-100/1__thumb_mobile.avif";
import mobileThumb120 from "@/assets/svoi-house/svoy-layt-004/1__thumb_mobile.avif";
import mobileThumb121 from "@/assets/svoi-house/svoy-102-m/1__thumb_mobile.avif";
import mobileThumb122 from "@/assets/bagrovstroy/9h15-dionis/1__thumb_mobile.avif";
import mobileThumb123 from "@/assets/bagrovstroy/9h15-sadko/1__thumb_mobile.avif";
import mobileThumb124 from "@/assets/bagrovstroy/10-5h11-avgust/1__thumb_mobile.avif";
import mobileThumb125 from "@/assets/bagrovstroy/6h8-saveliy/1__thumb_mobile.avif";
import mobileThumb126 from "@/assets/bagrovstroy/7h9-gostimir/1__thumb_mobile.avif";
import mobileThumb127 from "@/assets/domakarkas/kd-120/1__thumb_mobile.avif";
import mobileThumb128 from "@/assets/domakarkas/kd-119/1__thumb_mobile.avif";
import mobileThumb129 from "@/assets/domakarkas/kd-118/1__thumb_mobile.avif";
import mobileThumb130 from "@/assets/domakarkas/kd-117/1__thumb_mobile.avif";
import mobileThumb131 from "@/assets/domakarkas/kd-116/1__thumb_mobile.avif";
import mobileThumb132 from "@/assets/sk-garmoniya/vyazma/1__thumb_mobile.avif";
import mobileThumb133 from "@/assets/sk-garmoniya/sosnovyy-bor/1__thumb_mobile.avif";
import mobileThumb134 from "@/assets/sk-garmoniya/troitsk/1__thumb_mobile.avif";
import mobileThumb135 from "@/assets/sk-garmoniya/vyborg/1__thumb_mobile.avif";
import mobileThumb136 from "@/assets/sk-garmoniya/samara/1__thumb_mobile.avif";
import mobileThumb137 from "@/assets/berest-dom/bogatyr-lk-7h9/1__thumb_mobile.avif";
import mobileThumb138 from "@/assets/berest-dom/kareliya-2-7h9/1__thumb_mobile.avif";
import mobileThumb139 from "@/assets/berest-dom/senator-7-5h9/1__thumb_mobile.avif";
import mobileThumb140 from "@/assets/berest-dom/kareliya-1-7h8/1__thumb_mobile.avif";
import mobileThumb141 from "@/assets/berest-dom/senator-2-8-5h10-5/1__thumb_mobile.avif";
import mobileThumb142 from "@/assets/rift/dg51/1__thumb_mobile.avif";
import mobileThumb143 from "@/assets/rift/dg50/1__thumb_mobile.avif";
import mobileThumb144 from "@/assets/rift/xx27/1__thumb_mobile.avif";
import mobileThumb145 from "@/assets/rift/dg49/1__thumb_mobile.avif";
import mobileThumb146 from "@/assets/rift/xx05/1__thumb_mobile.avif";
import mobileThumb147 from "@/assets/izbrusa/kd-38/1__thumb_mobile.avif";
import mobileThumb148 from "@/assets/izbrusa/kd-29/1__thumb_mobile.avif";
import mobileThumb149 from "@/assets/izbrusa/kd-41/1__thumb_mobile.avif";
import mobileThumb150 from "@/assets/izbrusa/kd-12/1__thumb_mobile.avif";
import mobileThumb151 from "@/assets/izbrusa/kd-36/1__thumb_mobile.avif";
import mobileThumb152 from "@/assets/kazanstroy16/bigl/1__thumb_mobile.avif";
import mobileThumb153 from "@/assets/kazanstroy16/diotima/1__thumb_mobile.avif";
import mobileThumb154 from "@/assets/kazanstroy16/glenapp/1__thumb_mobile.avif";
import mobileThumb155 from "@/assets/kazanstroy16/strakeya/1__thumb_mobile.avif";
import mobileThumb156 from "@/assets/kazanstroy16/izabella/1__thumb_mobile.avif";
import mobileThumb157 from "@/assets/askhome/nova-prime/1__thumb_mobile.avif";
import mobileThumb158 from "@/assets/askhome/nova/1__thumb_mobile.avif";
import mobileThumb159 from "@/assets/askhome/modera-prime/1__thumb_mobile.avif";
import mobileThumb160 from "@/assets/askhome/modera/1__thumb_mobile.avif";
import mobileThumb161 from "@/assets/askhome/astra-prime/1__thumb_mobile.avif";
import mobileThumb162 from "@/assets/karkas-dom-yug/shale-67/1__thumb_mobile.avif";
import mobileThumb163 from "@/assets/karkas-dom-yug/shale-69/1__thumb_mobile.avif";
import mobileThumb164 from "@/assets/karkas-dom-yug/shale-65/1__thumb_mobile.avif";
import mobileThumb165 from "@/assets/karkas-dom-yug/shale-82/1__thumb_mobile.avif";
import mobileThumb166 from "@/assets/karkas-dom-yug/shale-90/1__thumb_mobile.avif";
import mobileThumb167 from "@/assets/sibiryak/barn-28/1__thumb_mobile.avif";
import mobileThumb168 from "@/assets/sibiryak/barn-41/1__thumb_mobile.avif";
import mobileThumb169 from "@/assets/sibiryak/barn-47/1__thumb_mobile.avif";
import mobileThumb170 from "@/assets/sibiryak/barn-95/1__thumb_mobile.avif";
import mobileThumb171 from "@/assets/sibiryak/barn-120/1__thumb_mobile.avif";
import mobileThumb172 from "@/assets/doma-ot-mihalycha/kulibin/1__thumb_mobile.avif";
import mobileThumb173 from "@/assets/doma-ot-mihalycha/lomonosov/1__thumb_mobile.avif";
import mobileThumb174 from "@/assets/doma-ot-mihalycha/rakhmaninov/1__thumb_mobile.avif";
import mobileThumb175 from "@/assets/doma-ot-mihalycha/derzhavin/1__thumb_mobile.avif";
import mobileThumb176 from "@/assets/doma-ot-mihalycha/vinogradov/1__thumb_mobile.avif";
import mobileThumb177 from "@/assets/barnstudio/opti/1__thumb_mobile.avif";
import mobileThumb178 from "@/assets/barnstudio/adel/1__thumb_mobile.avif";
import mobileThumb179 from "@/assets/barnstudio/alpina/1__thumb_mobile.avif";
import mobileThumb180 from "@/assets/barnstudio/antresol/1__thumb_mobile.avif";
import mobileThumb181 from "@/assets/barnstudio/vizhn/1__thumb_mobile.avif";
import mobileThumb182 from "@/assets/beli-dom/valdaj/1__thumb_mobile.avif";
import mobileThumb183 from "@/assets/beli-dom/semejnyj/1__thumb_mobile.avif";
import mobileThumb184 from "@/assets/beli-dom/tradicziya/1__thumb_mobile.avif";
import mobileThumb185 from "@/assets/beli-dom/karolina/1__thumb_mobile.avif";
import mobileThumb186 from "@/assets/beli-dom/triumf/1__thumb_mobile.avif";
import mobileThumb192 from "@/assets/mastergrupp-barnaul/angliya/01__thumb_mobile.avif";
import mobileThumb193 from "@/assets/mastergrupp-barnaul/klavdiya/01__thumb_mobile.avif";
import mobileThumb194 from "@/assets/mastergrupp-barnaul/vud/01__thumb_mobile.avif";
import mobileThumb195 from "@/assets/mastergrupp-barnaul/briksiya/01__thumb_mobile.avif";
import mobileThumb196 from "@/assets/mastergrupp-barnaul/burlakov/01__thumb_mobile.avif";
import mobileThumb197 from "@/assets/azbuka/zarya-75x8/1__thumb_mobile.avif";
import mobileThumb198 from "@/assets/azbuka/zarya-10x85/1__thumb_mobile.avif";
import mobileThumb199 from "@/assets/azbuka/zarya-11x85/1__thumb_mobile.avif";
import mobileThumb200 from "@/assets/azbuka/zarya-11x95/1__thumb_mobile.avif";
import mobileThumb201 from "@/assets/azbuka/zarya-9x9/1__thumb_mobile.avif";
import mobileThumb202 from "@/assets/rostdomik/krepost/1__thumb_mobile.avif";
import mobileThumb203 from "@/assets/rostdomik/angel/1__thumb_mobile.avif";
import mobileThumb204 from "@/assets/rostdomik/komfort-6x8/1__thumb_mobile.avif";
import mobileThumb205 from "@/assets/rostdomik/zhemchuzhina-mini/1__thumb_mobile.avif";
import mobileThumb206 from "@/assets/rostdomik/zhemchuzhina/1__thumb_mobile.avif";
import mobileThumb207 from "@/assets/klyuch-st/dom-6x6/1__thumb_mobile.avif";
import mobileThumb208 from "@/assets/klyuch-st/dom-6x9/1__thumb_mobile.avif";
import mobileThumb209 from "@/assets/klyuch-st/dom-5x7/1__thumb_mobile.avif";
import mobileThumb210 from "@/assets/klyuch-st/dom-6x8/1__thumb_mobile.avif";
import mobileThumb211 from "@/assets/klyuch-st/dom-8x12/1__thumb_mobile.avif";
import mobileThumb212 from "@/assets/doorhan/dom-29/1__thumb_mobile.avif";
import mobileThumb213 from "@/assets/doorhan/dom-44/1__thumb_mobile.avif";
import mobileThumb214 from "@/assets/doorhan/dom-59/1__thumb_mobile.avif";
import mobileThumb215 from "@/assets/doorhan/dom-74/1__thumb_mobile.avif";
import mobileThumb216 from "@/assets/doorhan/dom-88/1__thumb_mobile.avif";
import mobileThumb217 from "@/assets/avgst/barn-75/1__thumb_mobile.avif";
import mobileThumb218 from "@/assets/avgst/barn-134/1__thumb_mobile.avif";
import mobileThumb219 from "@/assets/avgst/ekokhaus-124/1__thumb_mobile.avif";
import mobileThumb220 from "@/assets/avgst/barn-74/1__thumb_mobile.avif";
import mobileThumb221 from "@/assets/avgst/barn-73/1__thumb_mobile.avif";
import mobileThumb222 from "@/assets/stroylider/kareliya-82/1__thumb_mobile.avif";
import mobileThumb223 from "@/assets/stroylider/kareliya-81/1__thumb_mobile.avif";
import mobileThumb224 from "@/assets/stroylider/kareliya-80/1__thumb_mobile.avif";
import mobileThumb225 from "@/assets/stroylider/kareliya-75/1__thumb_mobile.avif";
import mobileThumb226 from "@/assets/stroylider/kareliya-76/1__thumb_mobile.avif";
import mobileThumb227 from "@/assets/postroidom/forest-91/1__thumb_mobile.avif";
import mobileThumb228 from "@/assets/postroidom/forest-109/1__thumb_mobile.avif";
import mobileThumb229 from "@/assets/postroidom/forest-137/1__thumb_mobile.avif";
import mobileThumb230 from "@/assets/postroidom/forest-253/1__thumb_mobile.avif";
import mobileThumb231 from "@/assets/postroidom/aframe-50/1__thumb_mobile.avif";
import mobileThumb232 from "@/assets/altai-mda/oktyabr/1__thumb_mobile.avif";
import mobileThumb233 from "@/assets/altai-mda/aya/1__thumb_mobile.avif";
import mobileThumb234 from "@/assets/altai-mda/flora/1__thumb_mobile.avif";
import mobileThumb235 from "@/assets/altai-mda/uznezya/1__thumb_mobile.avif";
import mobileThumb236 from "@/assets/altai-mda/barantal/1__thumb_mobile.avif";
import mobileThumb237 from "@/assets/praktika-stroy/ps-praktik-21-1__thumb_mobile.avif";
import mobileThumb238 from "@/assets/praktika-stroy/ps-praktik-22-1__thumb_mobile.avif";
import mobileThumb239 from "@/assets/praktika-stroy/ps-praktik-23-1__thumb_mobile.avif";
import mobileThumb240 from "@/assets/praktika-stroy/ps-praktik-31-1__thumb_mobile.avif";
import mobileThumb241 from "@/assets/praktika-stroy/ps-praktik-32-1__thumb_mobile.avif";
import mobileThumb242 from "@/assets/eco-city/ec-mga-1__thumb_mobile.avif";
import mobileThumb243 from "@/assets/eco-city/ec-dunay-1__thumb_mobile.avif";
import mobileThumb244 from "@/assets/eco-city/ec-lammi-1__thumb_mobile.avif";
import mobileThumb245 from "@/assets/eco-city/ec-imatra-1__thumb_mobile.avif";
import mobileThumb246 from "@/assets/eco-city/ec-lahti-1__thumb_mobile.avif";
import mobileThumb247 from "@/assets/modom/mo-uno-1__thumb_mobile.avif";
import mobileThumb248 from "@/assets/modom/mo-o2-s-1__thumb_mobile.avif";
import mobileThumb249 from "@/assets/modom/mo-o2-m-1__thumb_mobile.avif";
import mobileThumb250 from "@/assets/modom/mo-o2-l-1__thumb_mobile.avif";
import mobileThumb251 from "@/assets/modom/mo-o2-mini30-1__thumb_mobile.avif";
import mobileThumb252 from "@/assets/housebox/hb-standart14-1__thumb_mobile.avif";
import mobileThumb253 from "@/assets/housebox/hb-standart14m-1__thumb_mobile.avif";
import mobileThumb254 from "@/assets/housebox/hb-standart19-1__thumb_mobile.avif";
import mobileThumb255 from "@/assets/glavles/gl-8-35/01__thumb_mobile.avif";
import mobileThumb256 from "@/assets/glavles/gl-8-27/01__thumb_mobile.avif";
import mobileThumb257 from "@/assets/glavles/gl-8-25/01__thumb_mobile.avif";
import mobileThumb258 from "@/assets/glavles/gl-8-68/01__thumb_mobile.avif";
import mobileThumb259 from "@/assets/glavles/gl-8-87/01__thumb_mobile.avif";
import mobileThumb260 from "@/assets/fps-modul/ah-281/01__thumb_mobile.avif";
import mobileThumb261 from "@/assets/fps-modul/ah-313/01__thumb_mobile.avif";
import mobileThumb262 from "@/assets/fps-modul/bh-411/01__thumb_mobile.avif";
import mobileThumb263 from "@/assets/fps-modul/bh-412/01__thumb_mobile.avif";
import mobileThumb264 from "@/assets/fps-modul/bh-403/01__thumb_mobile.avif";
import mobileThumb265 from "@/assets/vek-trad/m-98/01__thumb_mobile.avif";
import mobileThumb266 from "@/assets/vek-trad/m-85/01__thumb_mobile.avif";
import mobileThumb267 from "@/assets/vek-trad/m-73/01__thumb_mobile.avif";
import mobileThumb268 from "@/assets/vek-trad/m-60/01__thumb_mobile.avif";
import mobileThumb269 from "@/assets/budushiy-dom/hitech-45/01__thumb_mobile.avif";
import mobileThumb270 from "@/assets/budushiy-dom/hitech-36/01__thumb_mobile.avif";
import mobileThumb271 from "@/assets/budushiy-dom/barn-60f/01__thumb_mobile.avif";
import mobileThumb272 from "@/assets/budushiy-dom/dom-8/01__thumb_mobile.avif";
import mobileThumb273 from "@/assets/budushiy-dom/modual-75/01__thumb_mobile.avif";
import mobileThumb274 from "@/assets/qubdom/q/01__thumb_mobile.avif";
import mobileThumb275 from "@/assets/qubdom/q-plus/01__thumb_mobile.avif";
import mobileThumb276 from "@/assets/qubdom/q-family-mini/01__thumb_mobile.avif";
import mobileThumb277 from "@/assets/qubdom/q-family-max/01__thumb_mobile.avif";
import mobileThumb278 from "@/assets/qubdom/q-s-tamburom/01__thumb_mobile.avif";
import mobileThumb279 from "@/assets/durov-house/barn-dh21/01__thumb_mobile.avif";
import mobileThumb280 from "@/assets/durov-house/barn-dh57/01__thumb_mobile.avif";
import mobileThumb281 from "@/assets/durov-house/barn-dh64/01__thumb_mobile.avif";
import mobileThumb282 from "@/assets/durov-house/flat-dh67/01__thumb_mobile.avif";
import mobileThumb283 from "@/assets/durov-house/flat-dh124/01__thumb_mobile.avif";
import mobileThumb284 from "@/assets/histhut/hizhina-8/01__thumb_mobile.avif";
import mobileThumb285 from "@/assets/histhut/hizhina-10/01__thumb_mobile.avif";
import mobileThumb286 from "@/assets/histhut/hizhina-12/01__thumb_mobile.avif";
import mobileThumb287 from "@/assets/histhut/hizhina-20/01__thumb_mobile.avif";
import mobileThumb288 from "@/assets/histhut/hizhina-25/01__thumb_mobile.avif";
import mobileThumb294 from "@/assets/countryhouse/hitech-m1/01__thumb_mobile.avif";
import mobileThumb295 from "@/assets/countryhouse/hitech-m15/01__thumb_mobile.avif";
import mobileThumb296 from "@/assets/countryhouse/hitech-m2/01__thumb_mobile.avif";
import mobileThumb297 from "@/assets/countryhouse/hitech-m3/01__thumb_mobile.avif";
import mobileThumb298 from "@/assets/countryhouse/hitech-m5/01__thumb_mobile.avif";
import mobileThumb299 from "@/assets/cubadom/cuba-35-1/01__thumb_mobile.avif";
import mobileThumb300 from "@/assets/cubadom/cuba-35-2/01__thumb_mobile.avif";
import mobileThumb301 from "@/assets/cubadom/cuba-53-1/01__thumb_mobile.avif";
import mobileThumb302 from "@/assets/cubadom/cuba-53-2/01__thumb_mobile.avif";
import mobileThumb303 from "@/assets/cubadom/cuba-70-1/01__thumb_mobile.avif";
import mobileThumb304 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-36/01__thumb_mobile.avif";
import mobileThumb305 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-47/01__thumb_mobile.avif";
import mobileThumb306 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-62/01__thumb_mobile.avif";
import mobileThumb307 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-72/01__thumb_mobile.avif";
import mobileThumb308 from "@/assets/idolhouse/modul-nyy-dom-aydolhaus-86/01__thumb_mobile.avif";
import mobileThumb309 from "@/assets/woodalp/woodhouse-60-pro/01__thumb_mobile.avif";
import mobileThumb310 from "@/assets/woodalp/woodhouse-90-pro/01__thumb_mobile.avif";
import mobileThumb311 from "@/assets/woodalp/woodhouse-120-pro/01__thumb_mobile.avif";
import mobileThumb312 from "@/assets/boxmate/flat-5-box/01__thumb_mobile.avif";
import mobileThumb313 from "@/assets/boxmate/flat-4-box/01__thumb_mobile.avif";
import mobileThumb314 from "@/assets/boxmate/flat-3-box/01__thumb_mobile.avif";
import mobileThumb315 from "@/assets/boxmate/red-5-box/01__thumb_mobile.avif";
import mobileThumb316 from "@/assets/boxmate/red-4-box/01__thumb_mobile.avif";
import mobileThumb317 from "@/assets/uvhouse/mono-30/01__thumb_mobile.avif";
import mobileThumb318 from "@/assets/uvhouse/skandi-32/01__thumb_mobile.avif";
import mobileThumb319 from "@/assets/uvhouse/nord-40/01__thumb_mobile.avif";
import mobileThumb320 from "@/assets/uvhouse/shale-24/01__thumb_mobile.avif";
import mobileThumb321 from "@/assets/uvhouse/skandi-40/01__thumb_mobile.avif";
import mobileThumb322 from "@/assets/asterius/altair-20/01__thumb_mobile.avif";
import mobileThumb323 from "@/assets/asterius/altair-30/01__thumb_mobile.avif";
import mobileThumb324 from "@/assets/asterius/antares-40/01__thumb_mobile.avif";
import mobileThumb325 from "@/assets/asterius/antares-60/01__thumb_mobile.avif";
import mobileThumb326 from "@/assets/asterius/antares-80/01__thumb_mobile.avif";
import mobileThumb327 from "@/assets/smola/smola-103/01__thumb_mobile.avif";
import mobileThumb328 from "@/assets/smola/smola-65/01__thumb_mobile.avif";
import mobileThumb329 from "@/assets/smola/smola-77/01__thumb_mobile.avif";
import mobileThumb330 from "@/assets/smola/smola-43/01__thumb_mobile.avif";
import mobileThumb331 from "@/assets/ultradomspb/ultra-36/01__thumb_mobile.avif";
import mobileThumb332 from "@/assets/ultradomspb/ultra-54/01__thumb_mobile.avif";
import mobileThumb333 from "@/assets/ultradomspb/ultra-72/01__thumb_mobile.avif";
import mobileThumb334 from "@/assets/ultradomspb/ultra-65/01__thumb_mobile.avif";
import mobileThumb335 from "@/assets/ultradomspb/ultra-85/01__thumb_mobile.avif";
import mobileThumb336 from "@/assets/freedom/naturi-55/01__thumb_mobile.avif";
import mobileThumb337 from "@/assets/freedom/naturi-100/01__thumb_mobile.avif";
import mobileThumb338 from "@/assets/freedom/freedom-barn/01__thumb_mobile.avif";
import mobileThumb339 from "@/assets/chebwood/modul-15/01__thumb_mobile.avif";
import mobileThumb340 from "@/assets/chebwood/dom-pod-kluch/01__thumb_mobile.avif";
import mobileThumb341 from "@/assets/chebwood/glamping/01__thumb_mobile.avif";
import mobileThumb342 from "@/assets/campingdom/campingdom-15/01__thumb_mobile.avif";
import mobileThumb343 from "@/assets/campingdom/campingdom-22/01__thumb_mobile.avif";
import mobileThumb344 from "@/assets/campingdom/campingdom-32/01__thumb_mobile.avif";
import mobileThumb345 from "@/assets/campingdom/campingdom-15-barn/01__thumb_mobile.avif";
import mobileThumb346 from "@/assets/campingdom/campingdom-28-barn/01__thumb_mobile.avif";
import mobileThumb347 from "@/assets/pslcomp/barn-36/01__thumb_mobile.avif";
import mobileThumb348 from "@/assets/pslcomp/haytek-36/01__thumb_mobile.avif";
import mobileThumb349 from "@/assets/pslcomp/barn-40/01__thumb_mobile.avif";
import mobileThumb350 from "@/assets/pslcomp/haytek-40/01__thumb_mobile.avif";
import mobileThumb351 from "@/assets/pslcomp/barn-45/01__thumb_mobile.avif";
import mobileThumb352 from "@/assets/domnasm/domnas-35/01__thumb_mobile.avif";
import mobileThumb353 from "@/assets/domnasm/domnas-50/01__thumb_mobile.avif";
import mobileThumb354 from "@/assets/domnasm/domnas-80/01__thumb_mobile.avif";
import mobileThumb355 from "@/assets/domnasm/barn/01__thumb_mobile.avif";
import mobileThumb356 from "@/assets/domnasm/mgn/01__thumb_mobile.avif";
import mobileThumb357 from "@/assets/blackmodule/one-module/01__thumb_mobile.avif";
import mobileThumb358 from "@/assets/blackmodule/one-half-module/01__thumb_mobile.avif";
import mobileThumb359 from "@/assets/blackmodule/two-module/01__thumb_mobile.avif";
import mobileThumb360 from "@/assets/blackmodule/three-module/01__thumb_mobile.avif";
import mobileThumb361 from "@/assets/blackmodule/four-module/01__thumb_mobile.avif";
import mobileThumb362 from "@/assets/domm/modul-house-1/01__thumb_mobile.avif";
import mobileThumb363 from "@/assets/domm/modul-house-2/01__thumb_mobile.avif";
import mobileThumb364 from "@/assets/domm/modul-house-3/01__thumb_mobile.avif";
import mobileThumb365 from "@/assets/domm/modul-house-4/01__thumb_mobile.avif";
import mobileThumb366 from "@/assets/domm/modul-house-6/01__thumb_mobile.avif";
import mobileThumb367 from "@/assets/my-module/barni/01__thumb_mobile.avif";
import mobileThumb368 from "@/assets/my-module/korner/01__thumb_mobile.avif";
import mobileThumb369 from "@/assets/my-module/scandinavia/01__thumb_mobile.avif";
import mobileThumb370 from "@/assets/my-module/z/01__thumb_mobile.avif";
import mobileThumb371 from "@/assets/4modul/karelia-30/01__thumb_mobile.avif";
import mobileThumb372 from "@/assets/4modul/karelia-45/01__thumb_mobile.avif";
import mobileThumb373 from "@/assets/4modul/karelia-60/01__thumb_mobile.avif";
import mobileThumb374 from "@/assets/4modul/karelia-75/01__thumb_mobile.avif";
import mobileThumb375 from "@/assets/4modul/barn-60/01__thumb_mobile.avif";
import mobileThumb376 from "@/assets/cubber/house-48/01__thumb_mobile.avif";
import mobileThumb377 from "@/assets/cubber/house-50/01__thumb_mobile.avif";
import mobileThumb378 from "@/assets/cubber/house-60/01__thumb_mobile.avif";
import mobileThumb379 from "@/assets/cubber/house-65/01__thumb_mobile.avif";
import mobileThumb380 from "@/assets/cubber/house-95t/01__thumb_mobile.avif";
import mobileThumb381 from "@/assets/simplehouse/simple-6/01__thumb_mobile.avif";
import mobileThumb382 from "@/assets/panoramic-home/xl-54/01__thumb_mobile.avif";
import mobileThumb383 from "@/assets/panoramic-home/max-87/01__thumb_mobile.avif";
import mobileThumb384 from "@/assets/panoramic-home/xl-60/01__thumb_mobile.avif";
import mobileThumb385 from "@/assets/panoramic-home/xl-72/01__thumb_mobile.avif";
import mobileThumb386 from "@/assets/panoramic-home/xl-45/01__thumb_mobile.avif";
import mobileThumb387 from "@/assets/ambarn/barn-40-lux/01__thumb_mobile.avif";
import mobileThumb388 from "@/assets/ambarn/indigo-30/01__thumb_mobile.avif";
import mobileThumb389 from "@/assets/ambarn/indigo-40/01__thumb_mobile.avif";
import mobileThumb390 from "@/assets/ambarn/indigo-50/01__thumb_mobile.avif";
import mobileThumb391 from "@/assets/ambarn/indigo-36/01__thumb_mobile.avif";
import mobileThumb392 from "@/assets/myfamilyhouse/project-1/01__thumb_mobile.avif";
import mobileThumb393 from "@/assets/myfamilyhouse/project-2/01__thumb_mobile.avif";
import mobileThumb394 from "@/assets/myfamilyhouse/project-3/01__thumb_mobile.avif";
import mobileThumb395 from "@/assets/myfamilyhouse/project-4/01__thumb_mobile.avif";
import mobileThumb396 from "@/assets/myfamilyhouse/project-5/01__thumb_mobile.avif";
import mobileThumb397 from "@/assets/stroygrad/quattro-barn/01__thumb_mobile.avif";
import mobileThumb398 from "@/assets/stroygrad/sonin-lug/01__thumb_mobile.avif";
import mobileThumb399 from "@/assets/stroygrad/minidom/01__thumb_mobile.avif";
import mobileThumb400 from "@/assets/stroygrad/siete-offset/01__thumb_mobile.avif";
import mobileThumb401 from "@/assets/stroygrad/double-barn/01__thumb_mobile.avif";
import mobileThumb402 from "@/assets/modulcamp/barn-house/01__thumb_mobile.avif";
import mobileThumb403 from "@/assets/modulcamp/gollandiya/01__thumb_mobile.avif";
import mobileThumb404 from "@/assets/modulcamp/shale/01__thumb_mobile.avif";
import mobileThumb405 from "@/assets/modulcamp/finlandiya/01__thumb_mobile.avif";
import mobileThumb406 from "@/assets/modulcamp/daniya/01__thumb_mobile.avif";
import mobileThumb407 from "@/assets/elmaco/ivor/01__thumb_mobile.avif";
import mobileThumb408 from "@/assets/elmaco/lukas/01__thumb_mobile.avif";
import mobileThumb409 from "@/assets/elmaco/jung/01__thumb_mobile.avif";
import mobileThumb410 from "@/assets/elmaco/tor/01__thumb_mobile.avif";
import mobileThumb411 from "@/assets/elmaco/oscar/01__thumb_mobile.avif";
import mobileThumb412 from "@/assets/novator/radius/01__thumb_mobile.avif";
import mobileThumb413 from "@/assets/novator/n3/01__thumb_mobile.avif";
import mobileThumb414 from "@/assets/novator/n2/01__thumb_mobile.avif";
import mobileThumb415 from "@/assets/novator/n1/01__thumb_mobile.avif";
import mobileThumb416 from "@/assets/novator/n4/01__thumb_mobile.avif";
import mobileThumb417 from "@/assets/blagohouse/blagobarn-29/01__thumb_mobile.avif";
import mobileThumb418 from "@/assets/blagohouse/blagobarn-60/01__thumb_mobile.avif";
import mobileThumb419 from "@/assets/blagohouse/blagobarn-65/01__thumb_mobile.avif";
import mobileThumb420 from "@/assets/blagohouse/blagobarn-103/01__thumb_mobile.avif";
import mobileThumb421 from "@/assets/blagohouse/blagobarn-41/01__thumb_mobile.avif";
import mobileThumb422 from "@/assets/stilnye-moduli/double-s/01__thumb_mobile.avif";
import mobileThumb423 from "@/assets/stilnye-moduli/double-xs-terrace/01__thumb_mobile.avif";
import mobileThumb424 from "@/assets/stilnye-moduli/barnhaus-double/01__thumb_mobile.avif";
import mobileThumb425 from "@/assets/stilnye-moduli/triple-s-terrace/01__thumb_mobile.avif";
import mobileThumb426 from "@/assets/stilnye-moduli/quad/01__thumb_mobile.avif";
import mobileThumb427 from "@/assets/ip-modul/ip-40/01__thumb_mobile.avif";
import mobileThumb428 from "@/assets/ip-modul/ip-48/01__thumb_mobile.avif";
import mobileThumb429 from "@/assets/ip-modul/ip-60/01__thumb_mobile.avif";
import mobileThumb430 from "@/assets/ip-modul/ip-64/01__thumb_mobile.avif";
import mobileThumb431 from "@/assets/ip-modul/ip-72/01__thumb_mobile.avif";
import mobileThumb432 from "@/assets/rusmodul-spb/atreum-21/01__thumb_mobile.avif";
import mobileThumb433 from "@/assets/rusmodul-spb/atreum-28/01__thumb_mobile.avif";
import mobileThumb434 from "@/assets/rusmodul-spb/lodge-30/01__thumb_mobile.avif";
import mobileThumb435 from "@/assets/rusmodul-spb/double-lodge-50/01__thumb_mobile.avif";
import mobileThumb436 from "@/assets/rusmodul-spb/scandic-double-60/01__thumb_mobile.avif";
import mobileThumb437 from "@/assets/platforma-baths/bathhouse-01__thumb_mobile.avif";
import mobileThumb438 from "@/assets/platforma-baths/bathhouse-spa-01__thumb_mobile.avif";

export const projectThumbs: Record<number, string> = {
  31: thumb31,
  33: thumb33,
  34: thumb34,
  35: thumb35,
  36: thumb36,
  37: thumb37,
  38: thumb38,
  39: thumb39,
  40: thumb40,
  41: thumb41,
  42: thumb42,
  43: thumb43,
  44: thumb44,
  45: thumb45,
  46: thumb46,
  47: thumb47,
  48: thumb48,
  49: thumb49,
  50: thumb50,
  51: thumb51,
  52: thumb52,
  53: thumb53,
  54: thumb54,
  55: thumb55,
  56: thumb56,
  57: thumb57,
  58: thumb58,
  59: thumb59,
  60: thumb60,
  61: thumb61,
  62: thumb62,
  63: thumb63,
  64: thumb64,
  65: thumb65,
  66: thumb66,
  67: thumb67,
  68: thumb68,
  69: thumb69,
  70: thumb70,
  71: thumb71,
  72: thumb72,
  73: thumb73,
  74: thumb74,
  75: thumb75,
  76: thumb76,
  77: thumb77,
  78: thumb78,
  79: thumb79,
  80: thumb80,
  81: thumb81,
  82: thumb82,
  83: thumb83,
  84: thumb84,
  85: thumb85,
  86: thumb86,
  87: thumb87,
  88: thumb88,
  89: thumb89,
  90: thumb90,
  91: thumb91,
  92: thumb92,
  93: thumb93,
  94: thumb94,
  95: thumb95,
  96: thumb96,
  97: thumb97,
  98: thumb98,
  99: thumb99,
  100: thumb100,
  101: thumb101,
  102: thumb102,
  103: thumb103,
  104: thumb104,
  105: thumb105,
  106: thumb106,
  107: thumb107,
  108: thumb108,
  109: thumb109,
  110: thumb110,
  111: thumb111,
  112: thumb112,
  113: thumb113,
  114: thumb114,
  115: thumb115,
  116: thumb116,
  117: thumb117,
  118: thumb118,
  119: thumb119,
  120: thumb120,
  121: thumb121,
  122: thumb122,
  123: thumb123,
  124: thumb124,
  125: thumb125,
  126: thumb126,
  127: thumb127,
  128: thumb128,
  129: thumb129,
  130: thumb130,
  131: thumb131,
  132: thumb132,
  133: thumb133,
  134: thumb134,
  135: thumb135,
  136: thumb136,
  137: thumb137,
  138: thumb138,
  139: thumb139,
  140: thumb140,
  141: thumb141,
  142: thumb142,
  143: thumb143,
  144: thumb144,
  145: thumb145,
  146: thumb146,
  147: thumb147,
  148: thumb148,
  149: thumb149,
  150: thumb150,
  151: thumb151,
  152: thumb152,
  153: thumb153,
  154: thumb154,
  155: thumb155,
  156: thumb156,
  157: thumb157,
  158: thumb158,
  159: thumb159,
  160: thumb160,
  161: thumb161,
  162: thumb162,
  163: thumb163,
  164: thumb164,
  165: thumb165,
  166: thumb166,
  167: thumb167,
  168: thumb168,
  169: thumb169,
  170: thumb170,
  171: thumb171,
  172: thumb172,
  173: thumb173,
  174: thumb174,
  175: thumb175,
  176: thumb176,
  177: thumb177,
  178: thumb178,
  179: thumb179,
  180: thumb180,
  181: thumb181,
  182: thumb182,
  183: thumb183,
  184: thumb184,
  185: thumb185,
  186: thumb186,
  192: thumb192,
  193: thumb193,
  194: thumb194,
  195: thumb195,
  196: thumb196,
  197: thumb197,
  198: thumb198,
  199: thumb199,
  200: thumb200,
  201: thumb201,
  202: thumb202,
  203: thumb203,
  204: thumb204,
  205: thumb205,
  206: thumb206,
  207: thumb207,
  208: thumb208,
  209: thumb209,
  210: thumb210,
  211: thumb211,
  212: thumb212,
  213: thumb213,
  214: thumb214,
  215: thumb215,
  216: thumb216,
  217: thumb217,
  218: thumb218,
  219: thumb219,
  220: thumb220,
  221: thumb221,
  222: thumb222,
  223: thumb223,
  224: thumb224,
  225: thumb225,
  226: thumb226,
  227: thumb227,
  228: thumb228,
  229: thumb229,
  230: thumb230,
  231: thumb231,
  232: thumb232,
  233: thumb233,
  234: thumb234,
  235: thumb235,
  236: thumb236,
  237: thumb237,
  238: thumb238,
  239: thumb239,
  240: thumb240,
  241: thumb241,
  242: thumb242,
  243: thumb243,
  244: thumb244,
  245: thumb245,
  246: thumb246,
  247: thumb247,
  248: thumb248,
  249: thumb249,
  250: thumb250,
  251: thumb251,
  252: thumb252,
  253: thumb253,
  254: thumb254,
  255: thumb255,
  256: thumb256,
  257: thumb257,
  258: thumb258,
  259: thumb259,
  260: thumb260,
  261: thumb261,
  262: thumb262,
  263: thumb263,
  264: thumb264,
  265: thumb265,
  266: thumb266,
  267: thumb267,
  268: thumb268,
  269: thumb269,
  270: thumb270,
  271: thumb271,
  272: thumb272,
  273: thumb273,
  274: thumb274,
  275: thumb275,
  276: thumb276,
  277: thumb277,
  278: thumb278,
  279: thumb279,
  280: thumb280,
  281: thumb281,
  282: thumb282,
  283: thumb283,
  284: thumb284,
  285: thumb285,
  286: thumb286,
  287: thumb287,
  288: thumb288,
  294: thumb294,
  295: thumb295,
  296: thumb296,
  297: thumb297,
  298: thumb298,
  299: thumb299,
  300: thumb300,
  301: thumb301,
  302: thumb302,
  303: thumb303,
  304: thumb304,
  305: thumb305,
  306: thumb306,
  307: thumb307,
  308: thumb308,
  309: thumb309,
  310: thumb310,
  311: thumb311,
  312: thumb312,
  313: thumb313,
  314: thumb314,
  315: thumb315,
  316: thumb316,
  317: thumb317,
  318: thumb318,
  319: thumb319,
  320: thumb320,
  321: thumb321,
  322: thumb322,
  323: thumb323,
  324: thumb324,
  325: thumb325,
  326: thumb326,
  327: thumb327,
  328: thumb328,
  329: thumb329,
  330: thumb330,
  331: thumb331,
  332: thumb332,
  333: thumb333,
  334: thumb334,
  335: thumb335,
  336: thumb336,
  337: thumb337,
  338: thumb338,
  339: thumb339,
  340: thumb340,
  341: thumb341,
  342: thumb342,
  343: thumb343,
  344: thumb344,
  345: thumb345,
  346: thumb346,
  347: thumb347,
  348: thumb348,
  349: thumb349,
  350: thumb350,
  351: thumb351,
  352: thumb352,
  353: thumb353,
  354: thumb354,
  355: thumb355,
  356: thumb356,
  357: thumb357,
  358: thumb358,
  359: thumb359,
  360: thumb360,
  361: thumb361,
  362: thumb362,
  363: thumb363,
  364: thumb364,
  365: thumb365,
  366: thumb366,
  367: thumb367,
  368: thumb368,
  369: thumb369,
  370: thumb370,
  371: thumb371,
  372: thumb372,
  373: thumb373,
  374: thumb374,
  375: thumb375,
  376: thumb376,
  377: thumb377,
  378: thumb378,
  379: thumb379,
  380: thumb380,
  381: thumb381,
  382: thumb382,
  383: thumb383,
  384: thumb384,
  385: thumb385,
  386: thumb386,
  387: thumb387,
  388: thumb388,
  389: thumb389,
  390: thumb390,
  391: thumb391,
  392: thumb392,
  393: thumb393,
  394: thumb394,
  395: thumb395,
  396: thumb396,
  397: thumb397,
  398: thumb398,
  399: thumb399,
  400: thumb400,
  401: thumb401,
  402: thumb402,
  403: thumb403,
  404: thumb404,
  405: thumb405,
  406: thumb406,
  407: thumb407,
  408: thumb408,
  409: thumb409,
  410: thumb410,
  411: thumb411,
  412: thumb412,
  413: thumb413,
  414: thumb414,
  415: thumb415,
  416: thumb416,
  417: thumb417,
  418: thumb418,
  419: thumb419,
  420: thumb420,
  421: thumb421,
  422: thumb422,
  423: thumb423,
  424: thumb424,
  425: thumb425,
  426: thumb426,
  427: thumb427,
  428: thumb428,
  429: thumb429,
  430: thumb430,
  431: thumb431,
  432: thumb432,
  433: thumb433,
  434: thumb434,
  435: thumb435,
  436: thumb436,
  437: thumb437,
  438: thumb438,
};

export const projectMobileThumbs: Record<number, string> = {
  31: mobileThumb31,
  33: mobileThumb33,
  34: mobileThumb34,
  35: mobileThumb35,
  36: mobileThumb36,
  37: mobileThumb37,
  38: mobileThumb38,
  39: mobileThumb39,
  40: mobileThumb40,
  41: mobileThumb41,
  42: mobileThumb42,
  43: mobileThumb43,
  44: mobileThumb44,
  45: mobileThumb45,
  46: mobileThumb46,
  47: mobileThumb47,
  48: mobileThumb48,
  49: mobileThumb49,
  50: mobileThumb50,
  51: mobileThumb51,
  52: mobileThumb52,
  53: mobileThumb53,
  54: mobileThumb54,
  55: mobileThumb55,
  56: mobileThumb56,
  57: mobileThumb57,
  58: mobileThumb58,
  59: mobileThumb59,
  60: mobileThumb60,
  61: mobileThumb61,
  62: mobileThumb62,
  63: mobileThumb63,
  64: mobileThumb64,
  65: mobileThumb65,
  66: mobileThumb66,
  67: mobileThumb67,
  68: mobileThumb68,
  69: mobileThumb69,
  70: mobileThumb70,
  71: mobileThumb71,
  72: mobileThumb72,
  73: mobileThumb73,
  74: mobileThumb74,
  75: mobileThumb75,
  76: mobileThumb76,
  77: mobileThumb77,
  78: mobileThumb78,
  79: mobileThumb79,
  80: mobileThumb80,
  81: mobileThumb81,
  82: mobileThumb82,
  83: mobileThumb83,
  84: mobileThumb84,
  85: mobileThumb85,
  86: mobileThumb86,
  87: mobileThumb87,
  88: mobileThumb88,
  89: mobileThumb89,
  90: mobileThumb90,
  91: mobileThumb91,
  92: mobileThumb92,
  93: mobileThumb93,
  94: mobileThumb94,
  95: mobileThumb95,
  96: mobileThumb96,
  97: mobileThumb97,
  98: mobileThumb98,
  99: mobileThumb99,
  100: mobileThumb100,
  101: mobileThumb101,
  102: mobileThumb102,
  103: mobileThumb103,
  104: mobileThumb104,
  105: mobileThumb105,
  106: mobileThumb106,
  107: mobileThumb107,
  108: mobileThumb108,
  109: mobileThumb109,
  110: mobileThumb110,
  111: mobileThumb111,
  112: mobileThumb112,
  113: mobileThumb113,
  114: mobileThumb114,
  115: mobileThumb115,
  116: mobileThumb116,
  117: mobileThumb117,
  118: mobileThumb118,
  119: mobileThumb119,
  120: mobileThumb120,
  121: mobileThumb121,
  122: mobileThumb122,
  123: mobileThumb123,
  124: mobileThumb124,
  125: mobileThumb125,
  126: mobileThumb126,
  127: mobileThumb127,
  128: mobileThumb128,
  129: mobileThumb129,
  130: mobileThumb130,
  131: mobileThumb131,
  132: mobileThumb132,
  133: mobileThumb133,
  134: mobileThumb134,
  135: mobileThumb135,
  136: mobileThumb136,
  137: mobileThumb137,
  138: mobileThumb138,
  139: mobileThumb139,
  140: mobileThumb140,
  141: mobileThumb141,
  142: mobileThumb142,
  143: mobileThumb143,
  144: mobileThumb144,
  145: mobileThumb145,
  146: mobileThumb146,
  147: mobileThumb147,
  148: mobileThumb148,
  149: mobileThumb149,
  150: mobileThumb150,
  151: mobileThumb151,
  152: mobileThumb152,
  153: mobileThumb153,
  154: mobileThumb154,
  155: mobileThumb155,
  156: mobileThumb156,
  157: mobileThumb157,
  158: mobileThumb158,
  159: mobileThumb159,
  160: mobileThumb160,
  161: mobileThumb161,
  162: mobileThumb162,
  163: mobileThumb163,
  164: mobileThumb164,
  165: mobileThumb165,
  166: mobileThumb166,
  167: mobileThumb167,
  168: mobileThumb168,
  169: mobileThumb169,
  170: mobileThumb170,
  171: mobileThumb171,
  172: mobileThumb172,
  173: mobileThumb173,
  174: mobileThumb174,
  175: mobileThumb175,
  176: mobileThumb176,
  177: mobileThumb177,
  178: mobileThumb178,
  179: mobileThumb179,
  180: mobileThumb180,
  181: mobileThumb181,
  182: mobileThumb182,
  183: mobileThumb183,
  184: mobileThumb184,
  185: mobileThumb185,
  186: mobileThumb186,
  192: mobileThumb192,
  193: mobileThumb193,
  194: mobileThumb194,
  195: mobileThumb195,
  196: mobileThumb196,
  197: mobileThumb197,
  198: mobileThumb198,
  199: mobileThumb199,
  200: mobileThumb200,
  201: mobileThumb201,
  202: mobileThumb202,
  203: mobileThumb203,
  204: mobileThumb204,
  205: mobileThumb205,
  206: mobileThumb206,
  207: mobileThumb207,
  208: mobileThumb208,
  209: mobileThumb209,
  210: mobileThumb210,
  211: mobileThumb211,
  212: mobileThumb212,
  213: mobileThumb213,
  214: mobileThumb214,
  215: mobileThumb215,
  216: mobileThumb216,
  217: mobileThumb217,
  218: mobileThumb218,
  219: mobileThumb219,
  220: mobileThumb220,
  221: mobileThumb221,
  222: mobileThumb222,
  223: mobileThumb223,
  224: mobileThumb224,
  225: mobileThumb225,
  226: mobileThumb226,
  227: mobileThumb227,
  228: mobileThumb228,
  229: mobileThumb229,
  230: mobileThumb230,
  231: mobileThumb231,
  232: mobileThumb232,
  233: mobileThumb233,
  234: mobileThumb234,
  235: mobileThumb235,
  236: mobileThumb236,
  237: mobileThumb237,
  238: mobileThumb238,
  239: mobileThumb239,
  240: mobileThumb240,
  241: mobileThumb241,
  242: mobileThumb242,
  243: mobileThumb243,
  244: mobileThumb244,
  245: mobileThumb245,
  246: mobileThumb246,
  247: mobileThumb247,
  248: mobileThumb248,
  249: mobileThumb249,
  250: mobileThumb250,
  251: mobileThumb251,
  252: mobileThumb252,
  253: mobileThumb253,
  254: mobileThumb254,
  255: mobileThumb255,
  256: mobileThumb256,
  257: mobileThumb257,
  258: mobileThumb258,
  259: mobileThumb259,
  260: mobileThumb260,
  261: mobileThumb261,
  262: mobileThumb262,
  263: mobileThumb263,
  264: mobileThumb264,
  265: mobileThumb265,
  266: mobileThumb266,
  267: mobileThumb267,
  268: mobileThumb268,
  269: mobileThumb269,
  270: mobileThumb270,
  271: mobileThumb271,
  272: mobileThumb272,
  273: mobileThumb273,
  274: mobileThumb274,
  275: mobileThumb275,
  276: mobileThumb276,
  277: mobileThumb277,
  278: mobileThumb278,
  279: mobileThumb279,
  280: mobileThumb280,
  281: mobileThumb281,
  282: mobileThumb282,
  283: mobileThumb283,
  284: mobileThumb284,
  285: mobileThumb285,
  286: mobileThumb286,
  287: mobileThumb287,
  288: mobileThumb288,
  294: mobileThumb294,
  295: mobileThumb295,
  296: mobileThumb296,
  297: mobileThumb297,
  298: mobileThumb298,
  299: mobileThumb299,
  300: mobileThumb300,
  301: mobileThumb301,
  302: mobileThumb302,
  303: mobileThumb303,
  304: mobileThumb304,
  305: mobileThumb305,
  306: mobileThumb306,
  307: mobileThumb307,
  308: mobileThumb308,
  309: mobileThumb309,
  310: mobileThumb310,
  311: mobileThumb311,
  312: mobileThumb312,
  313: mobileThumb313,
  314: mobileThumb314,
  315: mobileThumb315,
  316: mobileThumb316,
  317: mobileThumb317,
  318: mobileThumb318,
  319: mobileThumb319,
  320: mobileThumb320,
  321: mobileThumb321,
  322: mobileThumb322,
  323: mobileThumb323,
  324: mobileThumb324,
  325: mobileThumb325,
  326: mobileThumb326,
  327: mobileThumb327,
  328: mobileThumb328,
  329: mobileThumb329,
  330: mobileThumb330,
  331: mobileThumb331,
  332: mobileThumb332,
  333: mobileThumb333,
  334: mobileThumb334,
  335: mobileThumb335,
  336: mobileThumb336,
  337: mobileThumb337,
  338: mobileThumb338,
  339: mobileThumb339,
  340: mobileThumb340,
  341: mobileThumb341,
  342: mobileThumb342,
  343: mobileThumb343,
  344: mobileThumb344,
  345: mobileThumb345,
  346: mobileThumb346,
  347: mobileThumb347,
  348: mobileThumb348,
  349: mobileThumb349,
  350: mobileThumb350,
  351: mobileThumb351,
  352: mobileThumb352,
  353: mobileThumb353,
  354: mobileThumb354,
  355: mobileThumb355,
  356: mobileThumb356,
  357: mobileThumb357,
  358: mobileThumb358,
  359: mobileThumb359,
  360: mobileThumb360,
  361: mobileThumb361,
  362: mobileThumb362,
  363: mobileThumb363,
  364: mobileThumb364,
  365: mobileThumb365,
  366: mobileThumb366,
  367: mobileThumb367,
  368: mobileThumb368,
  369: mobileThumb369,
  370: mobileThumb370,
  371: mobileThumb371,
  372: mobileThumb372,
  373: mobileThumb373,
  374: mobileThumb374,
  375: mobileThumb375,
  376: mobileThumb376,
  377: mobileThumb377,
  378: mobileThumb378,
  379: mobileThumb379,
  380: mobileThumb380,
  381: mobileThumb381,
  382: mobileThumb382,
  383: mobileThumb383,
  384: mobileThumb384,
  385: mobileThumb385,
  386: mobileThumb386,
  387: mobileThumb387,
  388: mobileThumb388,
  389: mobileThumb389,
  390: mobileThumb390,
  391: mobileThumb391,
  392: mobileThumb392,
  393: mobileThumb393,
  394: mobileThumb394,
  395: mobileThumb395,
  396: mobileThumb396,
  397: mobileThumb397,
  398: mobileThumb398,
  399: mobileThumb399,
  400: mobileThumb400,
  401: mobileThumb401,
  402: mobileThumb402,
  403: mobileThumb403,
  404: mobileThumb404,
  405: mobileThumb405,
  406: mobileThumb406,
  407: mobileThumb407,
  408: mobileThumb408,
  409: mobileThumb409,
  410: mobileThumb410,
  411: mobileThumb411,
  412: mobileThumb412,
  413: mobileThumb413,
  414: mobileThumb414,
  415: mobileThumb415,
  416: mobileThumb416,
  417: mobileThumb417,
  418: mobileThumb418,
  419: mobileThumb419,
  420: mobileThumb420,
  421: mobileThumb421,
  422: mobileThumb422,
  423: mobileThumb423,
  424: mobileThumb424,
  425: mobileThumb425,
  426: mobileThumb426,
  427: mobileThumb427,
  428: mobileThumb428,
  429: mobileThumb429,
  430: mobileThumb430,
  431: mobileThumb431,
  432: mobileThumb432,
  433: mobileThumb433,
  434: mobileThumb434,
  435: mobileThumb435,
  436: mobileThumb436,
  437: mobileThumb437,
  438: mobileThumb438,
};
